/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AdditionalRespondersAddAdditionalRespondersRequest = {
  incidentID: string;
  v3IncidentsAdditionalRespondersAddAdditionalRespondersRequest:
    models.V3IncidentsAdditionalRespondersAddAdditionalRespondersRequest;
};

/**
 * The request has succeeded.
 */
export type AdditionalRespondersAddAdditionalRespondersResponse = {
  data: models.V3IncidentsAdditionalRespondersAdditionalResponderResponse;
};

/** @internal */
export const AdditionalRespondersAddAdditionalRespondersRequest$inboundSchema:
  z.ZodType<
    AdditionalRespondersAddAdditionalRespondersRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    incidentID: z.string(),
    "V3.Incidents.AdditionalResponders.AddAdditionalRespondersRequest":
      models
        .V3IncidentsAdditionalRespondersAddAdditionalRespondersRequest$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "V3.Incidents.AdditionalResponders.AddAdditionalRespondersRequest":
        "v3IncidentsAdditionalRespondersAddAdditionalRespondersRequest",
    });
  });

/** @internal */
export type AdditionalRespondersAddAdditionalRespondersRequest$Outbound = {
  incidentID: string;
  "V3.Incidents.AdditionalResponders.AddAdditionalRespondersRequest":
    models.V3IncidentsAdditionalRespondersAddAdditionalRespondersRequest$Outbound;
};

/** @internal */
export const AdditionalRespondersAddAdditionalRespondersRequest$outboundSchema:
  z.ZodType<
    AdditionalRespondersAddAdditionalRespondersRequest$Outbound,
    z.ZodTypeDef,
    AdditionalRespondersAddAdditionalRespondersRequest
  > = z.object({
    incidentID: z.string(),
    v3IncidentsAdditionalRespondersAddAdditionalRespondersRequest:
      models
        .V3IncidentsAdditionalRespondersAddAdditionalRespondersRequest$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      v3IncidentsAdditionalRespondersAddAdditionalRespondersRequest:
        "V3.Incidents.AdditionalResponders.AddAdditionalRespondersRequest",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AdditionalRespondersAddAdditionalRespondersRequest$ {
  /** @deprecated use `AdditionalRespondersAddAdditionalRespondersRequest$inboundSchema` instead. */
  export const inboundSchema =
    AdditionalRespondersAddAdditionalRespondersRequest$inboundSchema;
  /** @deprecated use `AdditionalRespondersAddAdditionalRespondersRequest$outboundSchema` instead. */
  export const outboundSchema =
    AdditionalRespondersAddAdditionalRespondersRequest$outboundSchema;
  /** @deprecated use `AdditionalRespondersAddAdditionalRespondersRequest$Outbound` instead. */
  export type Outbound =
    AdditionalRespondersAddAdditionalRespondersRequest$Outbound;
}

export function additionalRespondersAddAdditionalRespondersRequestToJSON(
  additionalRespondersAddAdditionalRespondersRequest:
    AdditionalRespondersAddAdditionalRespondersRequest,
): string {
  return JSON.stringify(
    AdditionalRespondersAddAdditionalRespondersRequest$outboundSchema.parse(
      additionalRespondersAddAdditionalRespondersRequest,
    ),
  );
}

export function additionalRespondersAddAdditionalRespondersRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  AdditionalRespondersAddAdditionalRespondersRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AdditionalRespondersAddAdditionalRespondersRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AdditionalRespondersAddAdditionalRespondersRequest' from JSON`,
  );
}

/** @internal */
export const AdditionalRespondersAddAdditionalRespondersResponse$inboundSchema:
  z.ZodType<
    AdditionalRespondersAddAdditionalRespondersResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data:
      models
        .V3IncidentsAdditionalRespondersAdditionalResponderResponse$inboundSchema,
  });

/** @internal */
export type AdditionalRespondersAddAdditionalRespondersResponse$Outbound = {
  data:
    models.V3IncidentsAdditionalRespondersAdditionalResponderResponse$Outbound;
};

/** @internal */
export const AdditionalRespondersAddAdditionalRespondersResponse$outboundSchema:
  z.ZodType<
    AdditionalRespondersAddAdditionalRespondersResponse$Outbound,
    z.ZodTypeDef,
    AdditionalRespondersAddAdditionalRespondersResponse
  > = z.object({
    data:
      models
        .V3IncidentsAdditionalRespondersAdditionalResponderResponse$outboundSchema,
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AdditionalRespondersAddAdditionalRespondersResponse$ {
  /** @deprecated use `AdditionalRespondersAddAdditionalRespondersResponse$inboundSchema` instead. */
  export const inboundSchema =
    AdditionalRespondersAddAdditionalRespondersResponse$inboundSchema;
  /** @deprecated use `AdditionalRespondersAddAdditionalRespondersResponse$outboundSchema` instead. */
  export const outboundSchema =
    AdditionalRespondersAddAdditionalRespondersResponse$outboundSchema;
  /** @deprecated use `AdditionalRespondersAddAdditionalRespondersResponse$Outbound` instead. */
  export type Outbound =
    AdditionalRespondersAddAdditionalRespondersResponse$Outbound;
}

export function additionalRespondersAddAdditionalRespondersResponseToJSON(
  additionalRespondersAddAdditionalRespondersResponse:
    AdditionalRespondersAddAdditionalRespondersResponse,
): string {
  return JSON.stringify(
    AdditionalRespondersAddAdditionalRespondersResponse$outboundSchema.parse(
      additionalRespondersAddAdditionalRespondersResponse,
    ),
  );
}

export function additionalRespondersAddAdditionalRespondersResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  AdditionalRespondersAddAdditionalRespondersResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AdditionalRespondersAddAdditionalRespondersResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AdditionalRespondersAddAdditionalRespondersResponse' from JSON`,
  );
}
