/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AdditionalRespondersGetAdditionalRespondersRequest = {
  incidentID: string;
};

/**
 * The request has succeeded.
 */
export type AdditionalRespondersGetAdditionalRespondersResponse = {
  data: models.V3IncidentsAdditionalRespondersAdditionalResponderResponse;
};

/** @internal */
export const AdditionalRespondersGetAdditionalRespondersRequest$inboundSchema:
  z.ZodType<
    AdditionalRespondersGetAdditionalRespondersRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    incidentID: z.string(),
  });

/** @internal */
export type AdditionalRespondersGetAdditionalRespondersRequest$Outbound = {
  incidentID: string;
};

/** @internal */
export const AdditionalRespondersGetAdditionalRespondersRequest$outboundSchema:
  z.ZodType<
    AdditionalRespondersGetAdditionalRespondersRequest$Outbound,
    z.ZodTypeDef,
    AdditionalRespondersGetAdditionalRespondersRequest
  > = z.object({
    incidentID: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AdditionalRespondersGetAdditionalRespondersRequest$ {
  /** @deprecated use `AdditionalRespondersGetAdditionalRespondersRequest$inboundSchema` instead. */
  export const inboundSchema =
    AdditionalRespondersGetAdditionalRespondersRequest$inboundSchema;
  /** @deprecated use `AdditionalRespondersGetAdditionalRespondersRequest$outboundSchema` instead. */
  export const outboundSchema =
    AdditionalRespondersGetAdditionalRespondersRequest$outboundSchema;
  /** @deprecated use `AdditionalRespondersGetAdditionalRespondersRequest$Outbound` instead. */
  export type Outbound =
    AdditionalRespondersGetAdditionalRespondersRequest$Outbound;
}

export function additionalRespondersGetAdditionalRespondersRequestToJSON(
  additionalRespondersGetAdditionalRespondersRequest:
    AdditionalRespondersGetAdditionalRespondersRequest,
): string {
  return JSON.stringify(
    AdditionalRespondersGetAdditionalRespondersRequest$outboundSchema.parse(
      additionalRespondersGetAdditionalRespondersRequest,
    ),
  );
}

export function additionalRespondersGetAdditionalRespondersRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  AdditionalRespondersGetAdditionalRespondersRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AdditionalRespondersGetAdditionalRespondersRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AdditionalRespondersGetAdditionalRespondersRequest' from JSON`,
  );
}

/** @internal */
export const AdditionalRespondersGetAdditionalRespondersResponse$inboundSchema:
  z.ZodType<
    AdditionalRespondersGetAdditionalRespondersResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data:
      models
        .V3IncidentsAdditionalRespondersAdditionalResponderResponse$inboundSchema,
  });

/** @internal */
export type AdditionalRespondersGetAdditionalRespondersResponse$Outbound = {
  data:
    models.V3IncidentsAdditionalRespondersAdditionalResponderResponse$Outbound;
};

/** @internal */
export const AdditionalRespondersGetAdditionalRespondersResponse$outboundSchema:
  z.ZodType<
    AdditionalRespondersGetAdditionalRespondersResponse$Outbound,
    z.ZodTypeDef,
    AdditionalRespondersGetAdditionalRespondersResponse
  > = z.object({
    data:
      models
        .V3IncidentsAdditionalRespondersAdditionalResponderResponse$outboundSchema,
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AdditionalRespondersGetAdditionalRespondersResponse$ {
  /** @deprecated use `AdditionalRespondersGetAdditionalRespondersResponse$inboundSchema` instead. */
  export const inboundSchema =
    AdditionalRespondersGetAdditionalRespondersResponse$inboundSchema;
  /** @deprecated use `AdditionalRespondersGetAdditionalRespondersResponse$outboundSchema` instead. */
  export const outboundSchema =
    AdditionalRespondersGetAdditionalRespondersResponse$outboundSchema;
  /** @deprecated use `AdditionalRespondersGetAdditionalRespondersResponse$Outbound` instead. */
  export type Outbound =
    AdditionalRespondersGetAdditionalRespondersResponse$Outbound;
}

export function additionalRespondersGetAdditionalRespondersResponseToJSON(
  additionalRespondersGetAdditionalRespondersResponse:
    AdditionalRespondersGetAdditionalRespondersResponse,
): string {
  return JSON.stringify(
    AdditionalRespondersGetAdditionalRespondersResponse$outboundSchema.parse(
      additionalRespondersGetAdditionalRespondersResponse,
    ),
  );
}

export function additionalRespondersGetAdditionalRespondersResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  AdditionalRespondersGetAdditionalRespondersResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AdditionalRespondersGetAdditionalRespondersResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AdditionalRespondersGetAdditionalRespondersResponse' from JSON`,
  );
}
