/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AptaMarkAsNotTransientRequest = {
  incidentID: string;
};

/**
 * The request has succeeded.
 */
export type AptaMarkAsNotTransientResponse = {
  data: models.V3IncidentsAptaMessageResponse;
};

/** @internal */
export const AptaMarkAsNotTransientRequest$inboundSchema: z.ZodType<
  AptaMarkAsNotTransientRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  incidentID: z.string(),
});

/** @internal */
export type AptaMarkAsNotTransientRequest$Outbound = {
  incidentID: string;
};

/** @internal */
export const AptaMarkAsNotTransientRequest$outboundSchema: z.ZodType<
  AptaMarkAsNotTransientRequest$Outbound,
  z.ZodTypeDef,
  AptaMarkAsNotTransientRequest
> = z.object({
  incidentID: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AptaMarkAsNotTransientRequest$ {
  /** @deprecated use `AptaMarkAsNotTransientRequest$inboundSchema` instead. */
  export const inboundSchema = AptaMarkAsNotTransientRequest$inboundSchema;
  /** @deprecated use `AptaMarkAsNotTransientRequest$outboundSchema` instead. */
  export const outboundSchema = AptaMarkAsNotTransientRequest$outboundSchema;
  /** @deprecated use `AptaMarkAsNotTransientRequest$Outbound` instead. */
  export type Outbound = AptaMarkAsNotTransientRequest$Outbound;
}

export function aptaMarkAsNotTransientRequestToJSON(
  aptaMarkAsNotTransientRequest: AptaMarkAsNotTransientRequest,
): string {
  return JSON.stringify(
    AptaMarkAsNotTransientRequest$outboundSchema.parse(
      aptaMarkAsNotTransientRequest,
    ),
  );
}

export function aptaMarkAsNotTransientRequestFromJSON(
  jsonString: string,
): SafeParseResult<AptaMarkAsNotTransientRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AptaMarkAsNotTransientRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AptaMarkAsNotTransientRequest' from JSON`,
  );
}

/** @internal */
export const AptaMarkAsNotTransientResponse$inboundSchema: z.ZodType<
  AptaMarkAsNotTransientResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.V3IncidentsAptaMessageResponse$inboundSchema,
});

/** @internal */
export type AptaMarkAsNotTransientResponse$Outbound = {
  data: models.V3IncidentsAptaMessageResponse$Outbound;
};

/** @internal */
export const AptaMarkAsNotTransientResponse$outboundSchema: z.ZodType<
  AptaMarkAsNotTransientResponse$Outbound,
  z.ZodTypeDef,
  AptaMarkAsNotTransientResponse
> = z.object({
  data: models.V3IncidentsAptaMessageResponse$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AptaMarkAsNotTransientResponse$ {
  /** @deprecated use `AptaMarkAsNotTransientResponse$inboundSchema` instead. */
  export const inboundSchema = AptaMarkAsNotTransientResponse$inboundSchema;
  /** @deprecated use `AptaMarkAsNotTransientResponse$outboundSchema` instead. */
  export const outboundSchema = AptaMarkAsNotTransientResponse$outboundSchema;
  /** @deprecated use `AptaMarkAsNotTransientResponse$Outbound` instead. */
  export type Outbound = AptaMarkAsNotTransientResponse$Outbound;
}

export function aptaMarkAsNotTransientResponseToJSON(
  aptaMarkAsNotTransientResponse: AptaMarkAsNotTransientResponse,
): string {
  return JSON.stringify(
    AptaMarkAsNotTransientResponse$outboundSchema.parse(
      aptaMarkAsNotTransientResponse,
    ),
  );
}

export function aptaMarkAsNotTransientResponseFromJSON(
  jsonString: string,
): SafeParseResult<AptaMarkAsNotTransientResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AptaMarkAsNotTransientResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AptaMarkAsNotTransientResponse' from JSON`,
  );
}
