/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * The request has succeeded.
 */
export type CommunicationCardsArchiveSlackChannelResponse = {
  data: models.V3IncidentsCommunicationCardsCommunicationCardResponse;
};

/** @internal */
export const CommunicationCardsArchiveSlackChannelResponse$inboundSchema:
  z.ZodType<
    CommunicationCardsArchiveSlackChannelResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data:
      models
        .V3IncidentsCommunicationCardsCommunicationCardResponse$inboundSchema,
  });

/** @internal */
export type CommunicationCardsArchiveSlackChannelResponse$Outbound = {
  data: models.V3IncidentsCommunicationCardsCommunicationCardResponse$Outbound;
};

/** @internal */
export const CommunicationCardsArchiveSlackChannelResponse$outboundSchema:
  z.ZodType<
    CommunicationCardsArchiveSlackChannelResponse$Outbound,
    z.ZodTypeDef,
    CommunicationCardsArchiveSlackChannelResponse
  > = z.object({
    data:
      models
        .V3IncidentsCommunicationCardsCommunicationCardResponse$outboundSchema,
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CommunicationCardsArchiveSlackChannelResponse$ {
  /** @deprecated use `CommunicationCardsArchiveSlackChannelResponse$inboundSchema` instead. */
  export const inboundSchema =
    CommunicationCardsArchiveSlackChannelResponse$inboundSchema;
  /** @deprecated use `CommunicationCardsArchiveSlackChannelResponse$outboundSchema` instead. */
  export const outboundSchema =
    CommunicationCardsArchiveSlackChannelResponse$outboundSchema;
  /** @deprecated use `CommunicationCardsArchiveSlackChannelResponse$Outbound` instead. */
  export type Outbound = CommunicationCardsArchiveSlackChannelResponse$Outbound;
}

export function communicationCardsArchiveSlackChannelResponseToJSON(
  communicationCardsArchiveSlackChannelResponse:
    CommunicationCardsArchiveSlackChannelResponse,
): string {
  return JSON.stringify(
    CommunicationCardsArchiveSlackChannelResponse$outboundSchema.parse(
      communicationCardsArchiveSlackChannelResponse,
    ),
  );
}

export function communicationCardsArchiveSlackChannelResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  CommunicationCardsArchiveSlackChannelResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CommunicationCardsArchiveSlackChannelResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'CommunicationCardsArchiveSlackChannelResponse' from JSON`,
  );
}
