/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ComponentsDeleteComponentByIdRequest = {
  statuspageID: string;
  componentId: string;
};

/**
 * The request has succeeded.
 */
export type ComponentsDeleteComponentByIdResponse = {
  data: models.V4StatusPagesComponentsDeleteComponentByIdResponse;
};

/** @internal */
export const ComponentsDeleteComponentByIdRequest$inboundSchema: z.ZodType<
  ComponentsDeleteComponentByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  statuspageID: z.string(),
  component_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "component_id": "componentId",
  });
});

/** @internal */
export type ComponentsDeleteComponentByIdRequest$Outbound = {
  statuspageID: string;
  component_id: string;
};

/** @internal */
export const ComponentsDeleteComponentByIdRequest$outboundSchema: z.ZodType<
  ComponentsDeleteComponentByIdRequest$Outbound,
  z.ZodTypeDef,
  ComponentsDeleteComponentByIdRequest
> = z.object({
  statuspageID: z.string(),
  componentId: z.string(),
}).transform((v) => {
  return remap$(v, {
    componentId: "component_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ComponentsDeleteComponentByIdRequest$ {
  /** @deprecated use `ComponentsDeleteComponentByIdRequest$inboundSchema` instead. */
  export const inboundSchema =
    ComponentsDeleteComponentByIdRequest$inboundSchema;
  /** @deprecated use `ComponentsDeleteComponentByIdRequest$outboundSchema` instead. */
  export const outboundSchema =
    ComponentsDeleteComponentByIdRequest$outboundSchema;
  /** @deprecated use `ComponentsDeleteComponentByIdRequest$Outbound` instead. */
  export type Outbound = ComponentsDeleteComponentByIdRequest$Outbound;
}

export function componentsDeleteComponentByIdRequestToJSON(
  componentsDeleteComponentByIdRequest: ComponentsDeleteComponentByIdRequest,
): string {
  return JSON.stringify(
    ComponentsDeleteComponentByIdRequest$outboundSchema.parse(
      componentsDeleteComponentByIdRequest,
    ),
  );
}

export function componentsDeleteComponentByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<ComponentsDeleteComponentByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ComponentsDeleteComponentByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ComponentsDeleteComponentByIdRequest' from JSON`,
  );
}

/** @internal */
export const ComponentsDeleteComponentByIdResponse$inboundSchema: z.ZodType<
  ComponentsDeleteComponentByIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.V4StatusPagesComponentsDeleteComponentByIdResponse$inboundSchema,
});

/** @internal */
export type ComponentsDeleteComponentByIdResponse$Outbound = {
  data: models.V4StatusPagesComponentsDeleteComponentByIdResponse$Outbound;
};

/** @internal */
export const ComponentsDeleteComponentByIdResponse$outboundSchema: z.ZodType<
  ComponentsDeleteComponentByIdResponse$Outbound,
  z.ZodTypeDef,
  ComponentsDeleteComponentByIdResponse
> = z.object({
  data:
    models.V4StatusPagesComponentsDeleteComponentByIdResponse$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ComponentsDeleteComponentByIdResponse$ {
  /** @deprecated use `ComponentsDeleteComponentByIdResponse$inboundSchema` instead. */
  export const inboundSchema =
    ComponentsDeleteComponentByIdResponse$inboundSchema;
  /** @deprecated use `ComponentsDeleteComponentByIdResponse$outboundSchema` instead. */
  export const outboundSchema =
    ComponentsDeleteComponentByIdResponse$outboundSchema;
  /** @deprecated use `ComponentsDeleteComponentByIdResponse$Outbound` instead. */
  export type Outbound = ComponentsDeleteComponentByIdResponse$Outbound;
}

export function componentsDeleteComponentByIdResponseToJSON(
  componentsDeleteComponentByIdResponse: ComponentsDeleteComponentByIdResponse,
): string {
  return JSON.stringify(
    ComponentsDeleteComponentByIdResponse$outboundSchema.parse(
      componentsDeleteComponentByIdResponse,
    ),
  );
}

export function componentsDeleteComponentByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<ComponentsDeleteComponentByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ComponentsDeleteComponentByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ComponentsDeleteComponentByIdResponse' from JSON`,
  );
}
