/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type EscalationPoliciesRemoveEscalationPolicyRequest = {
  /**
   * (Required) escalation policy ID
   */
  escalationPolicyID: string;
};

/**
 * There is no content to send for this request, but the headers may be useful.
 */
export type EscalationPoliciesRemoveEscalationPolicyResponseBody = {};

/** @internal */
export const EscalationPoliciesRemoveEscalationPolicyRequest$inboundSchema:
  z.ZodType<
    EscalationPoliciesRemoveEscalationPolicyRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    escalationPolicyID: z.string(),
  });

/** @internal */
export type EscalationPoliciesRemoveEscalationPolicyRequest$Outbound = {
  escalationPolicyID: string;
};

/** @internal */
export const EscalationPoliciesRemoveEscalationPolicyRequest$outboundSchema:
  z.ZodType<
    EscalationPoliciesRemoveEscalationPolicyRequest$Outbound,
    z.ZodTypeDef,
    EscalationPoliciesRemoveEscalationPolicyRequest
  > = z.object({
    escalationPolicyID: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EscalationPoliciesRemoveEscalationPolicyRequest$ {
  /** @deprecated use `EscalationPoliciesRemoveEscalationPolicyRequest$inboundSchema` instead. */
  export const inboundSchema =
    EscalationPoliciesRemoveEscalationPolicyRequest$inboundSchema;
  /** @deprecated use `EscalationPoliciesRemoveEscalationPolicyRequest$outboundSchema` instead. */
  export const outboundSchema =
    EscalationPoliciesRemoveEscalationPolicyRequest$outboundSchema;
  /** @deprecated use `EscalationPoliciesRemoveEscalationPolicyRequest$Outbound` instead. */
  export type Outbound =
    EscalationPoliciesRemoveEscalationPolicyRequest$Outbound;
}

export function escalationPoliciesRemoveEscalationPolicyRequestToJSON(
  escalationPoliciesRemoveEscalationPolicyRequest:
    EscalationPoliciesRemoveEscalationPolicyRequest,
): string {
  return JSON.stringify(
    EscalationPoliciesRemoveEscalationPolicyRequest$outboundSchema.parse(
      escalationPoliciesRemoveEscalationPolicyRequest,
    ),
  );
}

export function escalationPoliciesRemoveEscalationPolicyRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  EscalationPoliciesRemoveEscalationPolicyRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      EscalationPoliciesRemoveEscalationPolicyRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'EscalationPoliciesRemoveEscalationPolicyRequest' from JSON`,
  );
}

/** @internal */
export const EscalationPoliciesRemoveEscalationPolicyResponseBody$inboundSchema:
  z.ZodType<
    EscalationPoliciesRemoveEscalationPolicyResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({});

/** @internal */
export type EscalationPoliciesRemoveEscalationPolicyResponseBody$Outbound = {};

/** @internal */
export const EscalationPoliciesRemoveEscalationPolicyResponseBody$outboundSchema:
  z.ZodType<
    EscalationPoliciesRemoveEscalationPolicyResponseBody$Outbound,
    z.ZodTypeDef,
    EscalationPoliciesRemoveEscalationPolicyResponseBody
  > = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EscalationPoliciesRemoveEscalationPolicyResponseBody$ {
  /** @deprecated use `EscalationPoliciesRemoveEscalationPolicyResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    EscalationPoliciesRemoveEscalationPolicyResponseBody$inboundSchema;
  /** @deprecated use `EscalationPoliciesRemoveEscalationPolicyResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    EscalationPoliciesRemoveEscalationPolicyResponseBody$outboundSchema;
  /** @deprecated use `EscalationPoliciesRemoveEscalationPolicyResponseBody$Outbound` instead. */
  export type Outbound =
    EscalationPoliciesRemoveEscalationPolicyResponseBody$Outbound;
}

export function escalationPoliciesRemoveEscalationPolicyResponseBodyToJSON(
  escalationPoliciesRemoveEscalationPolicyResponseBody:
    EscalationPoliciesRemoveEscalationPolicyResponseBody,
): string {
  return JSON.stringify(
    EscalationPoliciesRemoveEscalationPolicyResponseBody$outboundSchema.parse(
      escalationPoliciesRemoveEscalationPolicyResponseBody,
    ),
  );
}

export function escalationPoliciesRemoveEscalationPolicyResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  EscalationPoliciesRemoveEscalationPolicyResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      EscalationPoliciesRemoveEscalationPolicyResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'EscalationPoliciesRemoveEscalationPolicyResponseBody' from JSON`,
  );
}
