/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ExtensionsUpdateSlackExtensionRequest = {
  serviceID: string;
  v3ServicesExtensionsUpdateSlackExtensionRequest:
    models.V3ServicesExtensionsUpdateSlackExtensionRequest;
};

/**
 * The request has succeeded.
 */
export type ExtensionsUpdateSlackExtensionResponse = {
  data: models.V3ServicesExtensionsSlackExtensionResponse;
};

/** @internal */
export const ExtensionsUpdateSlackExtensionRequest$inboundSchema: z.ZodType<
  ExtensionsUpdateSlackExtensionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  serviceID: z.string(),
  "V3.Services.Extensions.UpdateSlackExtensionRequest":
    models.V3ServicesExtensionsUpdateSlackExtensionRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "V3.Services.Extensions.UpdateSlackExtensionRequest":
      "v3ServicesExtensionsUpdateSlackExtensionRequest",
  });
});

/** @internal */
export type ExtensionsUpdateSlackExtensionRequest$Outbound = {
  serviceID: string;
  "V3.Services.Extensions.UpdateSlackExtensionRequest":
    models.V3ServicesExtensionsUpdateSlackExtensionRequest$Outbound;
};

/** @internal */
export const ExtensionsUpdateSlackExtensionRequest$outboundSchema: z.ZodType<
  ExtensionsUpdateSlackExtensionRequest$Outbound,
  z.ZodTypeDef,
  ExtensionsUpdateSlackExtensionRequest
> = z.object({
  serviceID: z.string(),
  v3ServicesExtensionsUpdateSlackExtensionRequest:
    models.V3ServicesExtensionsUpdateSlackExtensionRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    v3ServicesExtensionsUpdateSlackExtensionRequest:
      "V3.Services.Extensions.UpdateSlackExtensionRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ExtensionsUpdateSlackExtensionRequest$ {
  /** @deprecated use `ExtensionsUpdateSlackExtensionRequest$inboundSchema` instead. */
  export const inboundSchema =
    ExtensionsUpdateSlackExtensionRequest$inboundSchema;
  /** @deprecated use `ExtensionsUpdateSlackExtensionRequest$outboundSchema` instead. */
  export const outboundSchema =
    ExtensionsUpdateSlackExtensionRequest$outboundSchema;
  /** @deprecated use `ExtensionsUpdateSlackExtensionRequest$Outbound` instead. */
  export type Outbound = ExtensionsUpdateSlackExtensionRequest$Outbound;
}

export function extensionsUpdateSlackExtensionRequestToJSON(
  extensionsUpdateSlackExtensionRequest: ExtensionsUpdateSlackExtensionRequest,
): string {
  return JSON.stringify(
    ExtensionsUpdateSlackExtensionRequest$outboundSchema.parse(
      extensionsUpdateSlackExtensionRequest,
    ),
  );
}

export function extensionsUpdateSlackExtensionRequestFromJSON(
  jsonString: string,
): SafeParseResult<ExtensionsUpdateSlackExtensionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ExtensionsUpdateSlackExtensionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExtensionsUpdateSlackExtensionRequest' from JSON`,
  );
}

/** @internal */
export const ExtensionsUpdateSlackExtensionResponse$inboundSchema: z.ZodType<
  ExtensionsUpdateSlackExtensionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.V3ServicesExtensionsSlackExtensionResponse$inboundSchema,
});

/** @internal */
export type ExtensionsUpdateSlackExtensionResponse$Outbound = {
  data: models.V3ServicesExtensionsSlackExtensionResponse$Outbound;
};

/** @internal */
export const ExtensionsUpdateSlackExtensionResponse$outboundSchema: z.ZodType<
  ExtensionsUpdateSlackExtensionResponse$Outbound,
  z.ZodTypeDef,
  ExtensionsUpdateSlackExtensionResponse
> = z.object({
  data: models.V3ServicesExtensionsSlackExtensionResponse$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ExtensionsUpdateSlackExtensionResponse$ {
  /** @deprecated use `ExtensionsUpdateSlackExtensionResponse$inboundSchema` instead. */
  export const inboundSchema =
    ExtensionsUpdateSlackExtensionResponse$inboundSchema;
  /** @deprecated use `ExtensionsUpdateSlackExtensionResponse$outboundSchema` instead. */
  export const outboundSchema =
    ExtensionsUpdateSlackExtensionResponse$outboundSchema;
  /** @deprecated use `ExtensionsUpdateSlackExtensionResponse$Outbound` instead. */
  export type Outbound = ExtensionsUpdateSlackExtensionResponse$Outbound;
}

export function extensionsUpdateSlackExtensionResponseToJSON(
  extensionsUpdateSlackExtensionResponse:
    ExtensionsUpdateSlackExtensionResponse,
): string {
  return JSON.stringify(
    ExtensionsUpdateSlackExtensionResponse$outboundSchema.parse(
      extensionsUpdateSlackExtensionResponse,
    ),
  );
}

export function extensionsUpdateSlackExtensionResponseFromJSON(
  jsonString: string,
): SafeParseResult<ExtensionsUpdateSlackExtensionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ExtensionsUpdateSlackExtensionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExtensionsUpdateSlackExtensionResponse' from JSON`,
  );
}
