/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest = {
  ownerId: string;
  v3GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest:
    models.V3GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest;
};

/**
 * The request has succeeded.
 */
export type GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesResponse = {
  data: models.V3GlobalOncallReminderRulesGlobalOncallReminderRuleResponse;
};

/** @internal */
export const GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest$inboundSchema:
  z.ZodType<
    GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    owner_id: z.string(),
    "V3.GlobalOncallReminderRules.UpdateGlobalOncallReminderRulesRequest":
      models
        .V3GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "owner_id": "ownerId",
      "V3.GlobalOncallReminderRules.UpdateGlobalOncallReminderRulesRequest":
        "v3GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest",
    });
  });

/** @internal */
export type GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest$Outbound =
  {
    owner_id: string;
    "V3.GlobalOncallReminderRules.UpdateGlobalOncallReminderRulesRequest":
      models.V3GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest$Outbound;
  };

/** @internal */
export const GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest$outboundSchema:
  z.ZodType<
    GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest$Outbound,
    z.ZodTypeDef,
    GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest
  > = z.object({
    ownerId: z.string(),
    v3GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest:
      models
        .V3GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      ownerId: "owner_id",
      v3GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest:
        "V3.GlobalOncallReminderRules.UpdateGlobalOncallReminderRulesRequest",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest$ {
  /** @deprecated use `GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest$inboundSchema` instead. */
  export const inboundSchema =
    GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest$inboundSchema;
  /** @deprecated use `GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest$outboundSchema` instead. */
  export const outboundSchema =
    GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest$outboundSchema;
  /** @deprecated use `GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest$Outbound` instead. */
  export type Outbound =
    GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest$Outbound;
}

export function globalOncallReminderRulesUpdateGlobalOncallReminderRulesRequestToJSON(
  globalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest:
    GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest,
): string {
  return JSON.stringify(
    GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest$outboundSchema
      .parse(globalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest),
  );
}

export function globalOncallReminderRulesUpdateGlobalOncallReminderRulesRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest' from JSON`,
  );
}

/** @internal */
export const GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesResponse$inboundSchema:
  z.ZodType<
    GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data:
      models
        .V3GlobalOncallReminderRulesGlobalOncallReminderRuleResponse$inboundSchema,
  });

/** @internal */
export type GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesResponse$Outbound =
  {
    data:
      models.V3GlobalOncallReminderRulesGlobalOncallReminderRuleResponse$Outbound;
  };

/** @internal */
export const GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesResponse$outboundSchema:
  z.ZodType<
    GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesResponse$Outbound,
    z.ZodTypeDef,
    GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesResponse
  > = z.object({
    data:
      models
        .V3GlobalOncallReminderRulesGlobalOncallReminderRuleResponse$outboundSchema,
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesResponse$ {
  /** @deprecated use `GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesResponse$inboundSchema` instead. */
  export const inboundSchema =
    GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesResponse$inboundSchema;
  /** @deprecated use `GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesResponse$outboundSchema` instead. */
  export const outboundSchema =
    GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesResponse$outboundSchema;
  /** @deprecated use `GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesResponse$Outbound` instead. */
  export type Outbound =
    GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesResponse$Outbound;
}

export function globalOncallReminderRulesUpdateGlobalOncallReminderRulesResponseToJSON(
  globalOncallReminderRulesUpdateGlobalOncallReminderRulesResponse:
    GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesResponse,
): string {
  return JSON.stringify(
    GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesResponse$outboundSchema
      .parse(globalOncallReminderRulesUpdateGlobalOncallReminderRulesResponse),
  );
}

export function globalOncallReminderRulesUpdateGlobalOncallReminderRulesResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesResponse' from JSON`,
  );
}
