/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GlobalEventRulesReorderRulesetRequest = {
  gerId: number;
  alertSourceVersion: string;
  alertSourceShortname: string;
  v3GlobalEventRulesReorderRulesetRequest:
    models.V3GlobalEventRulesReorderRulesetRequest;
};

/**
 * The request has succeeded.
 */
export type GlobalEventRulesReorderRulesetResponse = {
  data: models.V3GlobalEventRulesOrderingResponse;
};

/** @internal */
export const GlobalEventRulesReorderRulesetRequest$inboundSchema: z.ZodType<
  GlobalEventRulesReorderRulesetRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ger_id: z.number().int(),
  alert_source_version: z.string(),
  alert_source_shortname: z.string(),
  "V3.GlobalEventRules.ReorderRulesetRequest":
    models.V3GlobalEventRulesReorderRulesetRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "ger_id": "gerId",
    "alert_source_version": "alertSourceVersion",
    "alert_source_shortname": "alertSourceShortname",
    "V3.GlobalEventRules.ReorderRulesetRequest":
      "v3GlobalEventRulesReorderRulesetRequest",
  });
});

/** @internal */
export type GlobalEventRulesReorderRulesetRequest$Outbound = {
  ger_id: number;
  alert_source_version: string;
  alert_source_shortname: string;
  "V3.GlobalEventRules.ReorderRulesetRequest":
    models.V3GlobalEventRulesReorderRulesetRequest$Outbound;
};

/** @internal */
export const GlobalEventRulesReorderRulesetRequest$outboundSchema: z.ZodType<
  GlobalEventRulesReorderRulesetRequest$Outbound,
  z.ZodTypeDef,
  GlobalEventRulesReorderRulesetRequest
> = z.object({
  gerId: z.number().int(),
  alertSourceVersion: z.string(),
  alertSourceShortname: z.string(),
  v3GlobalEventRulesReorderRulesetRequest:
    models.V3GlobalEventRulesReorderRulesetRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    gerId: "ger_id",
    alertSourceVersion: "alert_source_version",
    alertSourceShortname: "alert_source_shortname",
    v3GlobalEventRulesReorderRulesetRequest:
      "V3.GlobalEventRules.ReorderRulesetRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GlobalEventRulesReorderRulesetRequest$ {
  /** @deprecated use `GlobalEventRulesReorderRulesetRequest$inboundSchema` instead. */
  export const inboundSchema =
    GlobalEventRulesReorderRulesetRequest$inboundSchema;
  /** @deprecated use `GlobalEventRulesReorderRulesetRequest$outboundSchema` instead. */
  export const outboundSchema =
    GlobalEventRulesReorderRulesetRequest$outboundSchema;
  /** @deprecated use `GlobalEventRulesReorderRulesetRequest$Outbound` instead. */
  export type Outbound = GlobalEventRulesReorderRulesetRequest$Outbound;
}

export function globalEventRulesReorderRulesetRequestToJSON(
  globalEventRulesReorderRulesetRequest: GlobalEventRulesReorderRulesetRequest,
): string {
  return JSON.stringify(
    GlobalEventRulesReorderRulesetRequest$outboundSchema.parse(
      globalEventRulesReorderRulesetRequest,
    ),
  );
}

export function globalEventRulesReorderRulesetRequestFromJSON(
  jsonString: string,
): SafeParseResult<GlobalEventRulesReorderRulesetRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GlobalEventRulesReorderRulesetRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GlobalEventRulesReorderRulesetRequest' from JSON`,
  );
}

/** @internal */
export const GlobalEventRulesReorderRulesetResponse$inboundSchema: z.ZodType<
  GlobalEventRulesReorderRulesetResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.V3GlobalEventRulesOrderingResponse$inboundSchema,
});

/** @internal */
export type GlobalEventRulesReorderRulesetResponse$Outbound = {
  data: models.V3GlobalEventRulesOrderingResponse$Outbound;
};

/** @internal */
export const GlobalEventRulesReorderRulesetResponse$outboundSchema: z.ZodType<
  GlobalEventRulesReorderRulesetResponse$Outbound,
  z.ZodTypeDef,
  GlobalEventRulesReorderRulesetResponse
> = z.object({
  data: models.V3GlobalEventRulesOrderingResponse$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GlobalEventRulesReorderRulesetResponse$ {
  /** @deprecated use `GlobalEventRulesReorderRulesetResponse$inboundSchema` instead. */
  export const inboundSchema =
    GlobalEventRulesReorderRulesetResponse$inboundSchema;
  /** @deprecated use `GlobalEventRulesReorderRulesetResponse$outboundSchema` instead. */
  export const outboundSchema =
    GlobalEventRulesReorderRulesetResponse$outboundSchema;
  /** @deprecated use `GlobalEventRulesReorderRulesetResponse$Outbound` instead. */
  export type Outbound = GlobalEventRulesReorderRulesetResponse$Outbound;
}

export function globalEventRulesReorderRulesetResponseToJSON(
  globalEventRulesReorderRulesetResponse:
    GlobalEventRulesReorderRulesetResponse,
): string {
  return JSON.stringify(
    GlobalEventRulesReorderRulesetResponse$outboundSchema.parse(
      globalEventRulesReorderRulesetResponse,
    ),
  );
}

export function globalEventRulesReorderRulesetResponseFromJSON(
  jsonString: string,
): SafeParseResult<GlobalEventRulesReorderRulesetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GlobalEventRulesReorderRulesetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GlobalEventRulesReorderRulesetResponse' from JSON`,
  );
}
