/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type IncidentActionsCreateATicketOnJiraCloudRequest = {
  incidentID: string;
};

/**
 * The request has succeeded.
 */
export type IncidentActionsCreateATicketOnJiraCloudResponse = {
  data: string;
};

/** @internal */
export const IncidentActionsCreateATicketOnJiraCloudRequest$inboundSchema:
  z.ZodType<
    IncidentActionsCreateATicketOnJiraCloudRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    incidentID: z.string(),
  });

/** @internal */
export type IncidentActionsCreateATicketOnJiraCloudRequest$Outbound = {
  incidentID: string;
};

/** @internal */
export const IncidentActionsCreateATicketOnJiraCloudRequest$outboundSchema:
  z.ZodType<
    IncidentActionsCreateATicketOnJiraCloudRequest$Outbound,
    z.ZodTypeDef,
    IncidentActionsCreateATicketOnJiraCloudRequest
  > = z.object({
    incidentID: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IncidentActionsCreateATicketOnJiraCloudRequest$ {
  /** @deprecated use `IncidentActionsCreateATicketOnJiraCloudRequest$inboundSchema` instead. */
  export const inboundSchema =
    IncidentActionsCreateATicketOnJiraCloudRequest$inboundSchema;
  /** @deprecated use `IncidentActionsCreateATicketOnJiraCloudRequest$outboundSchema` instead. */
  export const outboundSchema =
    IncidentActionsCreateATicketOnJiraCloudRequest$outboundSchema;
  /** @deprecated use `IncidentActionsCreateATicketOnJiraCloudRequest$Outbound` instead. */
  export type Outbound =
    IncidentActionsCreateATicketOnJiraCloudRequest$Outbound;
}

export function incidentActionsCreateATicketOnJiraCloudRequestToJSON(
  incidentActionsCreateATicketOnJiraCloudRequest:
    IncidentActionsCreateATicketOnJiraCloudRequest,
): string {
  return JSON.stringify(
    IncidentActionsCreateATicketOnJiraCloudRequest$outboundSchema.parse(
      incidentActionsCreateATicketOnJiraCloudRequest,
    ),
  );
}

export function incidentActionsCreateATicketOnJiraCloudRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  IncidentActionsCreateATicketOnJiraCloudRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      IncidentActionsCreateATicketOnJiraCloudRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'IncidentActionsCreateATicketOnJiraCloudRequest' from JSON`,
  );
}

/** @internal */
export const IncidentActionsCreateATicketOnJiraCloudResponse$inboundSchema:
  z.ZodType<
    IncidentActionsCreateATicketOnJiraCloudResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: z.string(),
  });

/** @internal */
export type IncidentActionsCreateATicketOnJiraCloudResponse$Outbound = {
  data: string;
};

/** @internal */
export const IncidentActionsCreateATicketOnJiraCloudResponse$outboundSchema:
  z.ZodType<
    IncidentActionsCreateATicketOnJiraCloudResponse$Outbound,
    z.ZodTypeDef,
    IncidentActionsCreateATicketOnJiraCloudResponse
  > = z.object({
    data: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IncidentActionsCreateATicketOnJiraCloudResponse$ {
  /** @deprecated use `IncidentActionsCreateATicketOnJiraCloudResponse$inboundSchema` instead. */
  export const inboundSchema =
    IncidentActionsCreateATicketOnJiraCloudResponse$inboundSchema;
  /** @deprecated use `IncidentActionsCreateATicketOnJiraCloudResponse$outboundSchema` instead. */
  export const outboundSchema =
    IncidentActionsCreateATicketOnJiraCloudResponse$outboundSchema;
  /** @deprecated use `IncidentActionsCreateATicketOnJiraCloudResponse$Outbound` instead. */
  export type Outbound =
    IncidentActionsCreateATicketOnJiraCloudResponse$Outbound;
}

export function incidentActionsCreateATicketOnJiraCloudResponseToJSON(
  incidentActionsCreateATicketOnJiraCloudResponse:
    IncidentActionsCreateATicketOnJiraCloudResponse,
): string {
  return JSON.stringify(
    IncidentActionsCreateATicketOnJiraCloudResponse$outboundSchema.parse(
      incidentActionsCreateATicketOnJiraCloudResponse,
    ),
  );
}

export function incidentActionsCreateATicketOnJiraCloudResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  IncidentActionsCreateATicketOnJiraCloudResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      IncidentActionsCreateATicketOnJiraCloudResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'IncidentActionsCreateATicketOnJiraCloudResponse' from JSON`,
  );
}
