/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * There is no content to send for this request, but the headers may be useful.
 */
export type IncidentsBulkIncidentsPriorityUpdateResponseBody = {};

/** @internal */
export const IncidentsBulkIncidentsPriorityUpdateResponseBody$inboundSchema:
  z.ZodType<
    IncidentsBulkIncidentsPriorityUpdateResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({});

/** @internal */
export type IncidentsBulkIncidentsPriorityUpdateResponseBody$Outbound = {};

/** @internal */
export const IncidentsBulkIncidentsPriorityUpdateResponseBody$outboundSchema:
  z.ZodType<
    IncidentsBulkIncidentsPriorityUpdateResponseBody$Outbound,
    z.ZodTypeDef,
    IncidentsBulkIncidentsPriorityUpdateResponseBody
  > = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IncidentsBulkIncidentsPriorityUpdateResponseBody$ {
  /** @deprecated use `IncidentsBulkIncidentsPriorityUpdateResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    IncidentsBulkIncidentsPriorityUpdateResponseBody$inboundSchema;
  /** @deprecated use `IncidentsBulkIncidentsPriorityUpdateResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    IncidentsBulkIncidentsPriorityUpdateResponseBody$outboundSchema;
  /** @deprecated use `IncidentsBulkIncidentsPriorityUpdateResponseBody$Outbound` instead. */
  export type Outbound =
    IncidentsBulkIncidentsPriorityUpdateResponseBody$Outbound;
}

export function incidentsBulkIncidentsPriorityUpdateResponseBodyToJSON(
  incidentsBulkIncidentsPriorityUpdateResponseBody:
    IncidentsBulkIncidentsPriorityUpdateResponseBody,
): string {
  return JSON.stringify(
    IncidentsBulkIncidentsPriorityUpdateResponseBody$outboundSchema.parse(
      incidentsBulkIncidentsPriorityUpdateResponseBody,
    ),
  );
}

export function incidentsBulkIncidentsPriorityUpdateResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  IncidentsBulkIncidentsPriorityUpdateResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      IncidentsBulkIncidentsPriorityUpdateResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'IncidentsBulkIncidentsPriorityUpdateResponseBody' from JSON`,
  );
}
