/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type IncidentActionsCreateATicketOnJiraServerRequest = {
  incidentID: string;
};

/**
 * The request has succeeded.
 */
export type IncidentActionsCreateATicketOnJiraServerResponse = {
  data: string;
};

/** @internal */
export const IncidentActionsCreateATicketOnJiraServerRequest$inboundSchema:
  z.ZodType<
    IncidentActionsCreateATicketOnJiraServerRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    incidentID: z.string(),
  });

/** @internal */
export type IncidentActionsCreateATicketOnJiraServerRequest$Outbound = {
  incidentID: string;
};

/** @internal */
export const IncidentActionsCreateATicketOnJiraServerRequest$outboundSchema:
  z.ZodType<
    IncidentActionsCreateATicketOnJiraServerRequest$Outbound,
    z.ZodTypeDef,
    IncidentActionsCreateATicketOnJiraServerRequest
  > = z.object({
    incidentID: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IncidentActionsCreateATicketOnJiraServerRequest$ {
  /** @deprecated use `IncidentActionsCreateATicketOnJiraServerRequest$inboundSchema` instead. */
  export const inboundSchema =
    IncidentActionsCreateATicketOnJiraServerRequest$inboundSchema;
  /** @deprecated use `IncidentActionsCreateATicketOnJiraServerRequest$outboundSchema` instead. */
  export const outboundSchema =
    IncidentActionsCreateATicketOnJiraServerRequest$outboundSchema;
  /** @deprecated use `IncidentActionsCreateATicketOnJiraServerRequest$Outbound` instead. */
  export type Outbound =
    IncidentActionsCreateATicketOnJiraServerRequest$Outbound;
}

export function incidentActionsCreateATicketOnJiraServerRequestToJSON(
  incidentActionsCreateATicketOnJiraServerRequest:
    IncidentActionsCreateATicketOnJiraServerRequest,
): string {
  return JSON.stringify(
    IncidentActionsCreateATicketOnJiraServerRequest$outboundSchema.parse(
      incidentActionsCreateATicketOnJiraServerRequest,
    ),
  );
}

export function incidentActionsCreateATicketOnJiraServerRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  IncidentActionsCreateATicketOnJiraServerRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      IncidentActionsCreateATicketOnJiraServerRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'IncidentActionsCreateATicketOnJiraServerRequest' from JSON`,
  );
}

/** @internal */
export const IncidentActionsCreateATicketOnJiraServerResponse$inboundSchema:
  z.ZodType<
    IncidentActionsCreateATicketOnJiraServerResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: z.string(),
  });

/** @internal */
export type IncidentActionsCreateATicketOnJiraServerResponse$Outbound = {
  data: string;
};

/** @internal */
export const IncidentActionsCreateATicketOnJiraServerResponse$outboundSchema:
  z.ZodType<
    IncidentActionsCreateATicketOnJiraServerResponse$Outbound,
    z.ZodTypeDef,
    IncidentActionsCreateATicketOnJiraServerResponse
  > = z.object({
    data: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IncidentActionsCreateATicketOnJiraServerResponse$ {
  /** @deprecated use `IncidentActionsCreateATicketOnJiraServerResponse$inboundSchema` instead. */
  export const inboundSchema =
    IncidentActionsCreateATicketOnJiraServerResponse$inboundSchema;
  /** @deprecated use `IncidentActionsCreateATicketOnJiraServerResponse$outboundSchema` instead. */
  export const outboundSchema =
    IncidentActionsCreateATicketOnJiraServerResponse$outboundSchema;
  /** @deprecated use `IncidentActionsCreateATicketOnJiraServerResponse$Outbound` instead. */
  export type Outbound =
    IncidentActionsCreateATicketOnJiraServerResponse$Outbound;
}

export function incidentActionsCreateATicketOnJiraServerResponseToJSON(
  incidentActionsCreateATicketOnJiraServerResponse:
    IncidentActionsCreateATicketOnJiraServerResponse,
): string {
  return JSON.stringify(
    IncidentActionsCreateATicketOnJiraServerResponse$outboundSchema.parse(
      incidentActionsCreateATicketOnJiraServerResponse,
    ),
  );
}

export function incidentActionsCreateATicketOnJiraServerResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  IncidentActionsCreateATicketOnJiraServerResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      IncidentActionsCreateATicketOnJiraServerResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'IncidentActionsCreateATicketOnJiraServerResponse' from JSON`,
  );
}
