/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * The request has succeeded.
 */
export type MSTeamsCreateOrUpdateMsteamsConfigurationResponse = {
  /**
   * The request body for creating or updating an MS Teams extension configuration.
   */
  data: models.V3ExtensionsMSTeamsMSTeamsConfigResponse;
};

/** @internal */
export const MSTeamsCreateOrUpdateMsteamsConfigurationResponse$inboundSchema:
  z.ZodType<
    MSTeamsCreateOrUpdateMsteamsConfigurationResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: models.V3ExtensionsMSTeamsMSTeamsConfigResponse$inboundSchema,
  });

/** @internal */
export type MSTeamsCreateOrUpdateMsteamsConfigurationResponse$Outbound = {
  data: models.V3ExtensionsMSTeamsMSTeamsConfigResponse$Outbound;
};

/** @internal */
export const MSTeamsCreateOrUpdateMsteamsConfigurationResponse$outboundSchema:
  z.ZodType<
    MSTeamsCreateOrUpdateMsteamsConfigurationResponse$Outbound,
    z.ZodTypeDef,
    MSTeamsCreateOrUpdateMsteamsConfigurationResponse
  > = z.object({
    data: models.V3ExtensionsMSTeamsMSTeamsConfigResponse$outboundSchema,
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MSTeamsCreateOrUpdateMsteamsConfigurationResponse$ {
  /** @deprecated use `MSTeamsCreateOrUpdateMsteamsConfigurationResponse$inboundSchema` instead. */
  export const inboundSchema =
    MSTeamsCreateOrUpdateMsteamsConfigurationResponse$inboundSchema;
  /** @deprecated use `MSTeamsCreateOrUpdateMsteamsConfigurationResponse$outboundSchema` instead. */
  export const outboundSchema =
    MSTeamsCreateOrUpdateMsteamsConfigurationResponse$outboundSchema;
  /** @deprecated use `MSTeamsCreateOrUpdateMsteamsConfigurationResponse$Outbound` instead. */
  export type Outbound =
    MSTeamsCreateOrUpdateMsteamsConfigurationResponse$Outbound;
}

export function msTeamsCreateOrUpdateMsteamsConfigurationResponseToJSON(
  msTeamsCreateOrUpdateMsteamsConfigurationResponse:
    MSTeamsCreateOrUpdateMsteamsConfigurationResponse,
): string {
  return JSON.stringify(
    MSTeamsCreateOrUpdateMsteamsConfigurationResponse$outboundSchema.parse(
      msTeamsCreateOrUpdateMsteamsConfigurationResponse,
    ),
  );
}

export function msTeamsCreateOrUpdateMsteamsConfigurationResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  MSTeamsCreateOrUpdateMsteamsConfigurationResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      MSTeamsCreateOrUpdateMsteamsConfigurationResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'MSTeamsCreateOrUpdateMsteamsConfigurationResponse' from JSON`,
  );
}
