/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RunbooksRemoveRunbookRequest = {
  runbookID: string;
};

/**
 * There is no content to send for this request, but the headers may be useful.
 */
export type RunbooksRemoveRunbookResponseBody = {};

/** @internal */
export const RunbooksRemoveRunbookRequest$inboundSchema: z.ZodType<
  RunbooksRemoveRunbookRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  runbookID: z.string(),
});

/** @internal */
export type RunbooksRemoveRunbookRequest$Outbound = {
  runbookID: string;
};

/** @internal */
export const RunbooksRemoveRunbookRequest$outboundSchema: z.ZodType<
  RunbooksRemoveRunbookRequest$Outbound,
  z.ZodTypeDef,
  RunbooksRemoveRunbookRequest
> = z.object({
  runbookID: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RunbooksRemoveRunbookRequest$ {
  /** @deprecated use `RunbooksRemoveRunbookRequest$inboundSchema` instead. */
  export const inboundSchema = RunbooksRemoveRunbookRequest$inboundSchema;
  /** @deprecated use `RunbooksRemoveRunbookRequest$outboundSchema` instead. */
  export const outboundSchema = RunbooksRemoveRunbookRequest$outboundSchema;
  /** @deprecated use `RunbooksRemoveRunbookRequest$Outbound` instead. */
  export type Outbound = RunbooksRemoveRunbookRequest$Outbound;
}

export function runbooksRemoveRunbookRequestToJSON(
  runbooksRemoveRunbookRequest: RunbooksRemoveRunbookRequest,
): string {
  return JSON.stringify(
    RunbooksRemoveRunbookRequest$outboundSchema.parse(
      runbooksRemoveRunbookRequest,
    ),
  );
}

export function runbooksRemoveRunbookRequestFromJSON(
  jsonString: string,
): SafeParseResult<RunbooksRemoveRunbookRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RunbooksRemoveRunbookRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RunbooksRemoveRunbookRequest' from JSON`,
  );
}

/** @internal */
export const RunbooksRemoveRunbookResponseBody$inboundSchema: z.ZodType<
  RunbooksRemoveRunbookResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type RunbooksRemoveRunbookResponseBody$Outbound = {};

/** @internal */
export const RunbooksRemoveRunbookResponseBody$outboundSchema: z.ZodType<
  RunbooksRemoveRunbookResponseBody$Outbound,
  z.ZodTypeDef,
  RunbooksRemoveRunbookResponseBody
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RunbooksRemoveRunbookResponseBody$ {
  /** @deprecated use `RunbooksRemoveRunbookResponseBody$inboundSchema` instead. */
  export const inboundSchema = RunbooksRemoveRunbookResponseBody$inboundSchema;
  /** @deprecated use `RunbooksRemoveRunbookResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    RunbooksRemoveRunbookResponseBody$outboundSchema;
  /** @deprecated use `RunbooksRemoveRunbookResponseBody$Outbound` instead. */
  export type Outbound = RunbooksRemoveRunbookResponseBody$Outbound;
}

export function runbooksRemoveRunbookResponseBodyToJSON(
  runbooksRemoveRunbookResponseBody: RunbooksRemoveRunbookResponseBody,
): string {
  return JSON.stringify(
    RunbooksRemoveRunbookResponseBody$outboundSchema.parse(
      runbooksRemoveRunbookResponseBody,
    ),
  );
}

export function runbooksRemoveRunbookResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<RunbooksRemoveRunbookResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RunbooksRemoveRunbookResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RunbooksRemoveRunbookResponseBody' from JSON`,
  );
}
