/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ServicesCreateOrUpdateIAGConfigRequest = {
  serviceID: string;
  v3ServicesIAGConfigRequest: models.V3ServicesIAGConfigRequest;
};

export type ServicesCreateOrUpdateIAGConfigData = {
  msg: string;
};

/**
 * The request has succeeded.
 */
export type ServicesCreateOrUpdateIAGConfigResponse = {
  data: ServicesCreateOrUpdateIAGConfigData;
};

/** @internal */
export const ServicesCreateOrUpdateIAGConfigRequest$inboundSchema: z.ZodType<
  ServicesCreateOrUpdateIAGConfigRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  serviceID: z.string(),
  "V3.Services.IAGConfigRequest":
    models.V3ServicesIAGConfigRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "V3.Services.IAGConfigRequest": "v3ServicesIAGConfigRequest",
  });
});

/** @internal */
export type ServicesCreateOrUpdateIAGConfigRequest$Outbound = {
  serviceID: string;
  "V3.Services.IAGConfigRequest": models.V3ServicesIAGConfigRequest$Outbound;
};

/** @internal */
export const ServicesCreateOrUpdateIAGConfigRequest$outboundSchema: z.ZodType<
  ServicesCreateOrUpdateIAGConfigRequest$Outbound,
  z.ZodTypeDef,
  ServicesCreateOrUpdateIAGConfigRequest
> = z.object({
  serviceID: z.string(),
  v3ServicesIAGConfigRequest: models.V3ServicesIAGConfigRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    v3ServicesIAGConfigRequest: "V3.Services.IAGConfigRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ServicesCreateOrUpdateIAGConfigRequest$ {
  /** @deprecated use `ServicesCreateOrUpdateIAGConfigRequest$inboundSchema` instead. */
  export const inboundSchema =
    ServicesCreateOrUpdateIAGConfigRequest$inboundSchema;
  /** @deprecated use `ServicesCreateOrUpdateIAGConfigRequest$outboundSchema` instead. */
  export const outboundSchema =
    ServicesCreateOrUpdateIAGConfigRequest$outboundSchema;
  /** @deprecated use `ServicesCreateOrUpdateIAGConfigRequest$Outbound` instead. */
  export type Outbound = ServicesCreateOrUpdateIAGConfigRequest$Outbound;
}

export function servicesCreateOrUpdateIAGConfigRequestToJSON(
  servicesCreateOrUpdateIAGConfigRequest:
    ServicesCreateOrUpdateIAGConfigRequest,
): string {
  return JSON.stringify(
    ServicesCreateOrUpdateIAGConfigRequest$outboundSchema.parse(
      servicesCreateOrUpdateIAGConfigRequest,
    ),
  );
}

export function servicesCreateOrUpdateIAGConfigRequestFromJSON(
  jsonString: string,
): SafeParseResult<ServicesCreateOrUpdateIAGConfigRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ServicesCreateOrUpdateIAGConfigRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServicesCreateOrUpdateIAGConfigRequest' from JSON`,
  );
}

/** @internal */
export const ServicesCreateOrUpdateIAGConfigData$inboundSchema: z.ZodType<
  ServicesCreateOrUpdateIAGConfigData,
  z.ZodTypeDef,
  unknown
> = z.object({
  msg: z.string(),
});

/** @internal */
export type ServicesCreateOrUpdateIAGConfigData$Outbound = {
  msg: string;
};

/** @internal */
export const ServicesCreateOrUpdateIAGConfigData$outboundSchema: z.ZodType<
  ServicesCreateOrUpdateIAGConfigData$Outbound,
  z.ZodTypeDef,
  ServicesCreateOrUpdateIAGConfigData
> = z.object({
  msg: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ServicesCreateOrUpdateIAGConfigData$ {
  /** @deprecated use `ServicesCreateOrUpdateIAGConfigData$inboundSchema` instead. */
  export const inboundSchema =
    ServicesCreateOrUpdateIAGConfigData$inboundSchema;
  /** @deprecated use `ServicesCreateOrUpdateIAGConfigData$outboundSchema` instead. */
  export const outboundSchema =
    ServicesCreateOrUpdateIAGConfigData$outboundSchema;
  /** @deprecated use `ServicesCreateOrUpdateIAGConfigData$Outbound` instead. */
  export type Outbound = ServicesCreateOrUpdateIAGConfigData$Outbound;
}

export function servicesCreateOrUpdateIAGConfigDataToJSON(
  servicesCreateOrUpdateIAGConfigData: ServicesCreateOrUpdateIAGConfigData,
): string {
  return JSON.stringify(
    ServicesCreateOrUpdateIAGConfigData$outboundSchema.parse(
      servicesCreateOrUpdateIAGConfigData,
    ),
  );
}

export function servicesCreateOrUpdateIAGConfigDataFromJSON(
  jsonString: string,
): SafeParseResult<ServicesCreateOrUpdateIAGConfigData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ServicesCreateOrUpdateIAGConfigData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServicesCreateOrUpdateIAGConfigData' from JSON`,
  );
}

/** @internal */
export const ServicesCreateOrUpdateIAGConfigResponse$inboundSchema: z.ZodType<
  ServicesCreateOrUpdateIAGConfigResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => ServicesCreateOrUpdateIAGConfigData$inboundSchema),
});

/** @internal */
export type ServicesCreateOrUpdateIAGConfigResponse$Outbound = {
  data: ServicesCreateOrUpdateIAGConfigData$Outbound;
};

/** @internal */
export const ServicesCreateOrUpdateIAGConfigResponse$outboundSchema: z.ZodType<
  ServicesCreateOrUpdateIAGConfigResponse$Outbound,
  z.ZodTypeDef,
  ServicesCreateOrUpdateIAGConfigResponse
> = z.object({
  data: z.lazy(() => ServicesCreateOrUpdateIAGConfigData$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ServicesCreateOrUpdateIAGConfigResponse$ {
  /** @deprecated use `ServicesCreateOrUpdateIAGConfigResponse$inboundSchema` instead. */
  export const inboundSchema =
    ServicesCreateOrUpdateIAGConfigResponse$inboundSchema;
  /** @deprecated use `ServicesCreateOrUpdateIAGConfigResponse$outboundSchema` instead. */
  export const outboundSchema =
    ServicesCreateOrUpdateIAGConfigResponse$outboundSchema;
  /** @deprecated use `ServicesCreateOrUpdateIAGConfigResponse$Outbound` instead. */
  export type Outbound = ServicesCreateOrUpdateIAGConfigResponse$Outbound;
}

export function servicesCreateOrUpdateIAGConfigResponseToJSON(
  servicesCreateOrUpdateIAGConfigResponse:
    ServicesCreateOrUpdateIAGConfigResponse,
): string {
  return JSON.stringify(
    ServicesCreateOrUpdateIAGConfigResponse$outboundSchema.parse(
      servicesCreateOrUpdateIAGConfigResponse,
    ),
  );
}

export function servicesCreateOrUpdateIAGConfigResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ServicesCreateOrUpdateIAGConfigResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ServicesCreateOrUpdateIAGConfigResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ServicesCreateOrUpdateIAGConfigResponse' from JSON`,
  );
}
