/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type SLOGetSLOByIdRequest = {
  sloID: number;
  ownerId: string;
};

/**
 * The request has succeeded.
 */
export type SLOGetSLOByIdResponse = {
  data: models.V3SLOSLOWithInsightsResponse;
};

/** @internal */
export const SLOGetSLOByIdRequest$inboundSchema: z.ZodType<
  SLOGetSLOByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  sloID: z.number().int(),
  owner_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "owner_id": "ownerId",
  });
});

/** @internal */
export type SLOGetSLOByIdRequest$Outbound = {
  sloID: number;
  owner_id: string;
};

/** @internal */
export const SLOGetSLOByIdRequest$outboundSchema: z.ZodType<
  SLOGetSLOByIdRequest$Outbound,
  z.ZodTypeDef,
  SLOGetSLOByIdRequest
> = z.object({
  sloID: z.number().int(),
  ownerId: z.string(),
}).transform((v) => {
  return remap$(v, {
    ownerId: "owner_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SLOGetSLOByIdRequest$ {
  /** @deprecated use `SLOGetSLOByIdRequest$inboundSchema` instead. */
  export const inboundSchema = SLOGetSLOByIdRequest$inboundSchema;
  /** @deprecated use `SLOGetSLOByIdRequest$outboundSchema` instead. */
  export const outboundSchema = SLOGetSLOByIdRequest$outboundSchema;
  /** @deprecated use `SLOGetSLOByIdRequest$Outbound` instead. */
  export type Outbound = SLOGetSLOByIdRequest$Outbound;
}

export function sloGetSLOByIdRequestToJSON(
  sloGetSLOByIdRequest: SLOGetSLOByIdRequest,
): string {
  return JSON.stringify(
    SLOGetSLOByIdRequest$outboundSchema.parse(sloGetSLOByIdRequest),
  );
}

export function sloGetSLOByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<SLOGetSLOByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SLOGetSLOByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SLOGetSLOByIdRequest' from JSON`,
  );
}

/** @internal */
export const SLOGetSLOByIdResponse$inboundSchema: z.ZodType<
  SLOGetSLOByIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.V3SLOSLOWithInsightsResponse$inboundSchema,
});

/** @internal */
export type SLOGetSLOByIdResponse$Outbound = {
  data: models.V3SLOSLOWithInsightsResponse$Outbound;
};

/** @internal */
export const SLOGetSLOByIdResponse$outboundSchema: z.ZodType<
  SLOGetSLOByIdResponse$Outbound,
  z.ZodTypeDef,
  SLOGetSLOByIdResponse
> = z.object({
  data: models.V3SLOSLOWithInsightsResponse$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SLOGetSLOByIdResponse$ {
  /** @deprecated use `SLOGetSLOByIdResponse$inboundSchema` instead. */
  export const inboundSchema = SLOGetSLOByIdResponse$inboundSchema;
  /** @deprecated use `SLOGetSLOByIdResponse$outboundSchema` instead. */
  export const outboundSchema = SLOGetSLOByIdResponse$outboundSchema;
  /** @deprecated use `SLOGetSLOByIdResponse$Outbound` instead. */
  export type Outbound = SLOGetSLOByIdResponse$Outbound;
}

export function sloGetSLOByIdResponseToJSON(
  sloGetSLOByIdResponse: SLOGetSLOByIdResponse,
): string {
  return JSON.stringify(
    SLOGetSLOByIdResponse$outboundSchema.parse(sloGetSLOByIdResponse),
  );
}

export function sloGetSLOByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<SLOGetSLOByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SLOGetSLOByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SLOGetSLOByIdResponse' from JSON`,
  );
}
