/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SquadsDeleteSquadRequest = {
  squadID: string;
};

/**
 * There is no content to send for this request, but the headers may be useful.
 */
export type SquadsDeleteSquadResponseBody = {};

/** @internal */
export const SquadsDeleteSquadRequest$inboundSchema: z.ZodType<
  SquadsDeleteSquadRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  squadID: z.string(),
});

/** @internal */
export type SquadsDeleteSquadRequest$Outbound = {
  squadID: string;
};

/** @internal */
export const SquadsDeleteSquadRequest$outboundSchema: z.ZodType<
  SquadsDeleteSquadRequest$Outbound,
  z.ZodTypeDef,
  SquadsDeleteSquadRequest
> = z.object({
  squadID: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SquadsDeleteSquadRequest$ {
  /** @deprecated use `SquadsDeleteSquadRequest$inboundSchema` instead. */
  export const inboundSchema = SquadsDeleteSquadRequest$inboundSchema;
  /** @deprecated use `SquadsDeleteSquadRequest$outboundSchema` instead. */
  export const outboundSchema = SquadsDeleteSquadRequest$outboundSchema;
  /** @deprecated use `SquadsDeleteSquadRequest$Outbound` instead. */
  export type Outbound = SquadsDeleteSquadRequest$Outbound;
}

export function squadsDeleteSquadRequestToJSON(
  squadsDeleteSquadRequest: SquadsDeleteSquadRequest,
): string {
  return JSON.stringify(
    SquadsDeleteSquadRequest$outboundSchema.parse(squadsDeleteSquadRequest),
  );
}

export function squadsDeleteSquadRequestFromJSON(
  jsonString: string,
): SafeParseResult<SquadsDeleteSquadRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SquadsDeleteSquadRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SquadsDeleteSquadRequest' from JSON`,
  );
}

/** @internal */
export const SquadsDeleteSquadResponseBody$inboundSchema: z.ZodType<
  SquadsDeleteSquadResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type SquadsDeleteSquadResponseBody$Outbound = {};

/** @internal */
export const SquadsDeleteSquadResponseBody$outboundSchema: z.ZodType<
  SquadsDeleteSquadResponseBody$Outbound,
  z.ZodTypeDef,
  SquadsDeleteSquadResponseBody
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SquadsDeleteSquadResponseBody$ {
  /** @deprecated use `SquadsDeleteSquadResponseBody$inboundSchema` instead. */
  export const inboundSchema = SquadsDeleteSquadResponseBody$inboundSchema;
  /** @deprecated use `SquadsDeleteSquadResponseBody$outboundSchema` instead. */
  export const outboundSchema = SquadsDeleteSquadResponseBody$outboundSchema;
  /** @deprecated use `SquadsDeleteSquadResponseBody$Outbound` instead. */
  export type Outbound = SquadsDeleteSquadResponseBody$Outbound;
}

export function squadsDeleteSquadResponseBodyToJSON(
  squadsDeleteSquadResponseBody: SquadsDeleteSquadResponseBody,
): string {
  return JSON.stringify(
    SquadsDeleteSquadResponseBody$outboundSchema.parse(
      squadsDeleteSquadResponseBody,
    ),
  );
}

export function squadsDeleteSquadResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<SquadsDeleteSquadResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SquadsDeleteSquadResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SquadsDeleteSquadResponseBody' from JSON`,
  );
}
