/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type StatusPagesListStatusPagesRequest = {
  pageSize: number;
  pageNumber: number;
  filtersIsPublic: string;
  teamID: string;
};

export type StatusPagesListStatusPagesResponse = {
  result: models.V4StatusPagesListStatusPagesResponse;
};

/** @internal */
export const StatusPagesListStatusPagesRequest$inboundSchema: z.ZodType<
  StatusPagesListStatusPagesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  pageSize: z.number().int(),
  pageNumber: z.number().int(),
  "filters.isPublic": z.string(),
  teamID: z.string(),
}).transform((v) => {
  return remap$(v, {
    "filters.isPublic": "filtersIsPublic",
  });
});

/** @internal */
export type StatusPagesListStatusPagesRequest$Outbound = {
  pageSize: number;
  pageNumber: number;
  "filters.isPublic": string;
  teamID: string;
};

/** @internal */
export const StatusPagesListStatusPagesRequest$outboundSchema: z.ZodType<
  StatusPagesListStatusPagesRequest$Outbound,
  z.ZodTypeDef,
  StatusPagesListStatusPagesRequest
> = z.object({
  pageSize: z.number().int(),
  pageNumber: z.number().int(),
  filtersIsPublic: z.string(),
  teamID: z.string(),
}).transform((v) => {
  return remap$(v, {
    filtersIsPublic: "filters.isPublic",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace StatusPagesListStatusPagesRequest$ {
  /** @deprecated use `StatusPagesListStatusPagesRequest$inboundSchema` instead. */
  export const inboundSchema = StatusPagesListStatusPagesRequest$inboundSchema;
  /** @deprecated use `StatusPagesListStatusPagesRequest$outboundSchema` instead. */
  export const outboundSchema =
    StatusPagesListStatusPagesRequest$outboundSchema;
  /** @deprecated use `StatusPagesListStatusPagesRequest$Outbound` instead. */
  export type Outbound = StatusPagesListStatusPagesRequest$Outbound;
}

export function statusPagesListStatusPagesRequestToJSON(
  statusPagesListStatusPagesRequest: StatusPagesListStatusPagesRequest,
): string {
  return JSON.stringify(
    StatusPagesListStatusPagesRequest$outboundSchema.parse(
      statusPagesListStatusPagesRequest,
    ),
  );
}

export function statusPagesListStatusPagesRequestFromJSON(
  jsonString: string,
): SafeParseResult<StatusPagesListStatusPagesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StatusPagesListStatusPagesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StatusPagesListStatusPagesRequest' from JSON`,
  );
}

/** @internal */
export const StatusPagesListStatusPagesResponse$inboundSchema: z.ZodType<
  StatusPagesListStatusPagesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: models.V4StatusPagesListStatusPagesResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

/** @internal */
export type StatusPagesListStatusPagesResponse$Outbound = {
  Result: models.V4StatusPagesListStatusPagesResponse$Outbound;
};

/** @internal */
export const StatusPagesListStatusPagesResponse$outboundSchema: z.ZodType<
  StatusPagesListStatusPagesResponse$Outbound,
  z.ZodTypeDef,
  StatusPagesListStatusPagesResponse
> = z.object({
  result: models.V4StatusPagesListStatusPagesResponse$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace StatusPagesListStatusPagesResponse$ {
  /** @deprecated use `StatusPagesListStatusPagesResponse$inboundSchema` instead. */
  export const inboundSchema = StatusPagesListStatusPagesResponse$inboundSchema;
  /** @deprecated use `StatusPagesListStatusPagesResponse$outboundSchema` instead. */
  export const outboundSchema =
    StatusPagesListStatusPagesResponse$outboundSchema;
  /** @deprecated use `StatusPagesListStatusPagesResponse$Outbound` instead. */
  export type Outbound = StatusPagesListStatusPagesResponse$Outbound;
}

export function statusPagesListStatusPagesResponseToJSON(
  statusPagesListStatusPagesResponse: StatusPagesListStatusPagesResponse,
): string {
  return JSON.stringify(
    StatusPagesListStatusPagesResponse$outboundSchema.parse(
      statusPagesListStatusPagesResponse,
    ),
  );
}

export function statusPagesListStatusPagesResponseFromJSON(
  jsonString: string,
): SafeParseResult<StatusPagesListStatusPagesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      StatusPagesListStatusPagesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StatusPagesListStatusPagesResponse' from JSON`,
  );
}
