/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type TeamsGetAllTeamRolesRequest = {
  teamId: string;
};

/**
 * The request has succeeded.
 */
export type TeamsGetAllTeamRolesResponse = {
  data: Array<models.V3TeamsTeamRoleResponse>;
};

/** @internal */
export const TeamsGetAllTeamRolesRequest$inboundSchema: z.ZodType<
  TeamsGetAllTeamRolesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  teamId: z.string(),
});

/** @internal */
export type TeamsGetAllTeamRolesRequest$Outbound = {
  teamId: string;
};

/** @internal */
export const TeamsGetAllTeamRolesRequest$outboundSchema: z.ZodType<
  TeamsGetAllTeamRolesRequest$Outbound,
  z.ZodTypeDef,
  TeamsGetAllTeamRolesRequest
> = z.object({
  teamId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TeamsGetAllTeamRolesRequest$ {
  /** @deprecated use `TeamsGetAllTeamRolesRequest$inboundSchema` instead. */
  export const inboundSchema = TeamsGetAllTeamRolesRequest$inboundSchema;
  /** @deprecated use `TeamsGetAllTeamRolesRequest$outboundSchema` instead. */
  export const outboundSchema = TeamsGetAllTeamRolesRequest$outboundSchema;
  /** @deprecated use `TeamsGetAllTeamRolesRequest$Outbound` instead. */
  export type Outbound = TeamsGetAllTeamRolesRequest$Outbound;
}

export function teamsGetAllTeamRolesRequestToJSON(
  teamsGetAllTeamRolesRequest: TeamsGetAllTeamRolesRequest,
): string {
  return JSON.stringify(
    TeamsGetAllTeamRolesRequest$outboundSchema.parse(
      teamsGetAllTeamRolesRequest,
    ),
  );
}

export function teamsGetAllTeamRolesRequestFromJSON(
  jsonString: string,
): SafeParseResult<TeamsGetAllTeamRolesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TeamsGetAllTeamRolesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TeamsGetAllTeamRolesRequest' from JSON`,
  );
}

/** @internal */
export const TeamsGetAllTeamRolesResponse$inboundSchema: z.ZodType<
  TeamsGetAllTeamRolesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(models.V3TeamsTeamRoleResponse$inboundSchema),
});

/** @internal */
export type TeamsGetAllTeamRolesResponse$Outbound = {
  data: Array<models.V3TeamsTeamRoleResponse$Outbound>;
};

/** @internal */
export const TeamsGetAllTeamRolesResponse$outboundSchema: z.ZodType<
  TeamsGetAllTeamRolesResponse$Outbound,
  z.ZodTypeDef,
  TeamsGetAllTeamRolesResponse
> = z.object({
  data: z.array(models.V3TeamsTeamRoleResponse$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TeamsGetAllTeamRolesResponse$ {
  /** @deprecated use `TeamsGetAllTeamRolesResponse$inboundSchema` instead. */
  export const inboundSchema = TeamsGetAllTeamRolesResponse$inboundSchema;
  /** @deprecated use `TeamsGetAllTeamRolesResponse$outboundSchema` instead. */
  export const outboundSchema = TeamsGetAllTeamRolesResponse$outboundSchema;
  /** @deprecated use `TeamsGetAllTeamRolesResponse$Outbound` instead. */
  export type Outbound = TeamsGetAllTeamRolesResponse$Outbound;
}

export function teamsGetAllTeamRolesResponseToJSON(
  teamsGetAllTeamRolesResponse: TeamsGetAllTeamRolesResponse,
): string {
  return JSON.stringify(
    TeamsGetAllTeamRolesResponse$outboundSchema.parse(
      teamsGetAllTeamRolesResponse,
    ),
  );
}

export function teamsGetAllTeamRolesResponseFromJSON(
  jsonString: string,
): SafeParseResult<TeamsGetAllTeamRolesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TeamsGetAllTeamRolesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TeamsGetAllTeamRolesResponse' from JSON`,
  );
}
