/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * The request has succeeded and a new resource has been created as a result.
 */
export type TeamsCreateTeamResponse = {
  data: models.V3TeamsTeamResponse;
};

/** @internal */
export const TeamsCreateTeamResponse$inboundSchema: z.ZodType<
  TeamsCreateTeamResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.V3TeamsTeamResponse$inboundSchema,
});

/** @internal */
export type TeamsCreateTeamResponse$Outbound = {
  data: models.V3TeamsTeamResponse$Outbound;
};

/** @internal */
export const TeamsCreateTeamResponse$outboundSchema: z.ZodType<
  TeamsCreateTeamResponse$Outbound,
  z.ZodTypeDef,
  TeamsCreateTeamResponse
> = z.object({
  data: models.V3TeamsTeamResponse$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TeamsCreateTeamResponse$ {
  /** @deprecated use `TeamsCreateTeamResponse$inboundSchema` instead. */
  export const inboundSchema = TeamsCreateTeamResponse$inboundSchema;
  /** @deprecated use `TeamsCreateTeamResponse$outboundSchema` instead. */
  export const outboundSchema = TeamsCreateTeamResponse$outboundSchema;
  /** @deprecated use `TeamsCreateTeamResponse$Outbound` instead. */
  export type Outbound = TeamsCreateTeamResponse$Outbound;
}

export function teamsCreateTeamResponseToJSON(
  teamsCreateTeamResponse: TeamsCreateTeamResponse,
): string {
  return JSON.stringify(
    TeamsCreateTeamResponse$outboundSchema.parse(teamsCreateTeamResponse),
  );
}

export function teamsCreateTeamResponseFromJSON(
  jsonString: string,
): SafeParseResult<TeamsCreateTeamResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TeamsCreateTeamResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TeamsCreateTeamResponse' from JSON`,
  );
}
