/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * The request has succeeded.
 */
export type UsersGetAllTokensResponse = {
  data: Array<models.V3UsersApiTokenResponse>;
};

/** @internal */
export const UsersGetAllTokensResponse$inboundSchema: z.ZodType<
  UsersGetAllTokensResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(models.V3UsersApiTokenResponse$inboundSchema),
});

/** @internal */
export type UsersGetAllTokensResponse$Outbound = {
  data: Array<models.V3UsersApiTokenResponse$Outbound>;
};

/** @internal */
export const UsersGetAllTokensResponse$outboundSchema: z.ZodType<
  UsersGetAllTokensResponse$Outbound,
  z.ZodTypeDef,
  UsersGetAllTokensResponse
> = z.object({
  data: z.array(models.V3UsersApiTokenResponse$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UsersGetAllTokensResponse$ {
  /** @deprecated use `UsersGetAllTokensResponse$inboundSchema` instead. */
  export const inboundSchema = UsersGetAllTokensResponse$inboundSchema;
  /** @deprecated use `UsersGetAllTokensResponse$outboundSchema` instead. */
  export const outboundSchema = UsersGetAllTokensResponse$outboundSchema;
  /** @deprecated use `UsersGetAllTokensResponse$Outbound` instead. */
  export type Outbound = UsersGetAllTokensResponse$Outbound;
}

export function usersGetAllTokensResponseToJSON(
  usersGetAllTokensResponse: UsersGetAllTokensResponse,
): string {
  return JSON.stringify(
    UsersGetAllTokensResponse$outboundSchema.parse(usersGetAllTokensResponse),
  );
}

export function usersGetAllTokensResponseFromJSON(
  jsonString: string,
): SafeParseResult<UsersGetAllTokensResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UsersGetAllTokensResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UsersGetAllTokensResponse' from JSON`,
  );
}
