/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type WorkflowsDeleteWorkflowActionRequest = {
  workflowID: string;
  actionID: string;
};

/**
 * There is no content to send for this request, but the headers may be useful.
 */
export type WorkflowsDeleteWorkflowActionResponseBody = {};

/** @internal */
export const WorkflowsDeleteWorkflowActionRequest$inboundSchema: z.ZodType<
  WorkflowsDeleteWorkflowActionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  workflowID: z.string(),
  actionID: z.string(),
});

/** @internal */
export type WorkflowsDeleteWorkflowActionRequest$Outbound = {
  workflowID: string;
  actionID: string;
};

/** @internal */
export const WorkflowsDeleteWorkflowActionRequest$outboundSchema: z.ZodType<
  WorkflowsDeleteWorkflowActionRequest$Outbound,
  z.ZodTypeDef,
  WorkflowsDeleteWorkflowActionRequest
> = z.object({
  workflowID: z.string(),
  actionID: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WorkflowsDeleteWorkflowActionRequest$ {
  /** @deprecated use `WorkflowsDeleteWorkflowActionRequest$inboundSchema` instead. */
  export const inboundSchema =
    WorkflowsDeleteWorkflowActionRequest$inboundSchema;
  /** @deprecated use `WorkflowsDeleteWorkflowActionRequest$outboundSchema` instead. */
  export const outboundSchema =
    WorkflowsDeleteWorkflowActionRequest$outboundSchema;
  /** @deprecated use `WorkflowsDeleteWorkflowActionRequest$Outbound` instead. */
  export type Outbound = WorkflowsDeleteWorkflowActionRequest$Outbound;
}

export function workflowsDeleteWorkflowActionRequestToJSON(
  workflowsDeleteWorkflowActionRequest: WorkflowsDeleteWorkflowActionRequest,
): string {
  return JSON.stringify(
    WorkflowsDeleteWorkflowActionRequest$outboundSchema.parse(
      workflowsDeleteWorkflowActionRequest,
    ),
  );
}

export function workflowsDeleteWorkflowActionRequestFromJSON(
  jsonString: string,
): SafeParseResult<WorkflowsDeleteWorkflowActionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      WorkflowsDeleteWorkflowActionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorkflowsDeleteWorkflowActionRequest' from JSON`,
  );
}

/** @internal */
export const WorkflowsDeleteWorkflowActionResponseBody$inboundSchema: z.ZodType<
  WorkflowsDeleteWorkflowActionResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type WorkflowsDeleteWorkflowActionResponseBody$Outbound = {};

/** @internal */
export const WorkflowsDeleteWorkflowActionResponseBody$outboundSchema:
  z.ZodType<
    WorkflowsDeleteWorkflowActionResponseBody$Outbound,
    z.ZodTypeDef,
    WorkflowsDeleteWorkflowActionResponseBody
  > = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WorkflowsDeleteWorkflowActionResponseBody$ {
  /** @deprecated use `WorkflowsDeleteWorkflowActionResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    WorkflowsDeleteWorkflowActionResponseBody$inboundSchema;
  /** @deprecated use `WorkflowsDeleteWorkflowActionResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    WorkflowsDeleteWorkflowActionResponseBody$outboundSchema;
  /** @deprecated use `WorkflowsDeleteWorkflowActionResponseBody$Outbound` instead. */
  export type Outbound = WorkflowsDeleteWorkflowActionResponseBody$Outbound;
}

export function workflowsDeleteWorkflowActionResponseBodyToJSON(
  workflowsDeleteWorkflowActionResponseBody:
    WorkflowsDeleteWorkflowActionResponseBody,
): string {
  return JSON.stringify(
    WorkflowsDeleteWorkflowActionResponseBody$outboundSchema.parse(
      workflowsDeleteWorkflowActionResponseBody,
    ),
  );
}

export function workflowsDeleteWorkflowActionResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  WorkflowsDeleteWorkflowActionResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      WorkflowsDeleteWorkflowActionResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'WorkflowsDeleteWorkflowActionResponseBody' from JSON`,
  );
}
