/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type WorkflowsUpdateActionsOrderRequest = {
  workflowID: string;
  v3WorkflowsUpdateActionsOrderRequest:
    models.V3WorkflowsUpdateActionsOrderRequest;
};

/** @internal */
export const WorkflowsUpdateActionsOrderRequest$inboundSchema: z.ZodType<
  WorkflowsUpdateActionsOrderRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  workflowID: z.string(),
  "V3.Workflows.UpdateActionsOrderRequest":
    models.V3WorkflowsUpdateActionsOrderRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "V3.Workflows.UpdateActionsOrderRequest":
      "v3WorkflowsUpdateActionsOrderRequest",
  });
});

/** @internal */
export type WorkflowsUpdateActionsOrderRequest$Outbound = {
  workflowID: string;
  "V3.Workflows.UpdateActionsOrderRequest":
    models.V3WorkflowsUpdateActionsOrderRequest$Outbound;
};

/** @internal */
export const WorkflowsUpdateActionsOrderRequest$outboundSchema: z.ZodType<
  WorkflowsUpdateActionsOrderRequest$Outbound,
  z.ZodTypeDef,
  WorkflowsUpdateActionsOrderRequest
> = z.object({
  workflowID: z.string(),
  v3WorkflowsUpdateActionsOrderRequest:
    models.V3WorkflowsUpdateActionsOrderRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    v3WorkflowsUpdateActionsOrderRequest:
      "V3.Workflows.UpdateActionsOrderRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WorkflowsUpdateActionsOrderRequest$ {
  /** @deprecated use `WorkflowsUpdateActionsOrderRequest$inboundSchema` instead. */
  export const inboundSchema = WorkflowsUpdateActionsOrderRequest$inboundSchema;
  /** @deprecated use `WorkflowsUpdateActionsOrderRequest$outboundSchema` instead. */
  export const outboundSchema =
    WorkflowsUpdateActionsOrderRequest$outboundSchema;
  /** @deprecated use `WorkflowsUpdateActionsOrderRequest$Outbound` instead. */
  export type Outbound = WorkflowsUpdateActionsOrderRequest$Outbound;
}

export function workflowsUpdateActionsOrderRequestToJSON(
  workflowsUpdateActionsOrderRequest: WorkflowsUpdateActionsOrderRequest,
): string {
  return JSON.stringify(
    WorkflowsUpdateActionsOrderRequest$outboundSchema.parse(
      workflowsUpdateActionsOrderRequest,
    ),
  );
}

export function workflowsUpdateActionsOrderRequestFromJSON(
  jsonString: string,
): SafeParseResult<WorkflowsUpdateActionsOrderRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      WorkflowsUpdateActionsOrderRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorkflowsUpdateActionsOrderRequest' from JSON`,
  );
}
