/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * There is no content to send for this request, but the headers may be useful.
 */
export type WorkflowsBulkEnabledisableWorkflowsResponseBody = {};

/** @internal */
export const WorkflowsBulkEnabledisableWorkflowsResponseBody$inboundSchema:
  z.ZodType<
    WorkflowsBulkEnabledisableWorkflowsResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({});

/** @internal */
export type WorkflowsBulkEnabledisableWorkflowsResponseBody$Outbound = {};

/** @internal */
export const WorkflowsBulkEnabledisableWorkflowsResponseBody$outboundSchema:
  z.ZodType<
    WorkflowsBulkEnabledisableWorkflowsResponseBody$Outbound,
    z.ZodTypeDef,
    WorkflowsBulkEnabledisableWorkflowsResponseBody
  > = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WorkflowsBulkEnabledisableWorkflowsResponseBody$ {
  /** @deprecated use `WorkflowsBulkEnabledisableWorkflowsResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    WorkflowsBulkEnabledisableWorkflowsResponseBody$inboundSchema;
  /** @deprecated use `WorkflowsBulkEnabledisableWorkflowsResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    WorkflowsBulkEnabledisableWorkflowsResponseBody$outboundSchema;
  /** @deprecated use `WorkflowsBulkEnabledisableWorkflowsResponseBody$Outbound` instead. */
  export type Outbound =
    WorkflowsBulkEnabledisableWorkflowsResponseBody$Outbound;
}

export function workflowsBulkEnabledisableWorkflowsResponseBodyToJSON(
  workflowsBulkEnabledisableWorkflowsResponseBody:
    WorkflowsBulkEnabledisableWorkflowsResponseBody,
): string {
  return JSON.stringify(
    WorkflowsBulkEnabledisableWorkflowsResponseBody$outboundSchema.parse(
      workflowsBulkEnabledisableWorkflowsResponseBody,
    ),
  );
}

export function workflowsBulkEnabledisableWorkflowsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  WorkflowsBulkEnabledisableWorkflowsResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      WorkflowsBulkEnabledisableWorkflowsResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'WorkflowsBulkEnabledisableWorkflowsResponseBody' from JSON`,
  );
}
