/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type Status = string | number;

/**
 * Represents a single response containing data of type T.
 */
export type CommonV3ErrorMeta = {
  status: string | number;
  errorMessage: string;
};

/** @internal */
export const Status$inboundSchema: z.ZodType<Status, z.ZodTypeDef, unknown> = z
  .union([z.string(), z.number().int()]);

/** @internal */
export type Status$Outbound = string | number;

/** @internal */
export const Status$outboundSchema: z.ZodType<
  Status$Outbound,
  z.ZodTypeDef,
  Status
> = z.union([z.string(), z.number().int()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Status$ {
  /** @deprecated use `Status$inboundSchema` instead. */
  export const inboundSchema = Status$inboundSchema;
  /** @deprecated use `Status$outboundSchema` instead. */
  export const outboundSchema = Status$outboundSchema;
  /** @deprecated use `Status$Outbound` instead. */
  export type Outbound = Status$Outbound;
}

export function statusToJSON(status: Status): string {
  return JSON.stringify(Status$outboundSchema.parse(status));
}

export function statusFromJSON(
  jsonString: string,
): SafeParseResult<Status, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Status$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Status' from JSON`,
  );
}

/** @internal */
export const CommonV3ErrorMeta$inboundSchema: z.ZodType<
  CommonV3ErrorMeta,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.union([z.string(), z.number().int()]),
  error_message: z.string(),
}).transform((v) => {
  return remap$(v, {
    "error_message": "errorMessage",
  });
});

/** @internal */
export type CommonV3ErrorMeta$Outbound = {
  status: string | number;
  error_message: string;
};

/** @internal */
export const CommonV3ErrorMeta$outboundSchema: z.ZodType<
  CommonV3ErrorMeta$Outbound,
  z.ZodTypeDef,
  CommonV3ErrorMeta
> = z.object({
  status: z.union([z.string(), z.number().int()]),
  errorMessage: z.string(),
}).transform((v) => {
  return remap$(v, {
    errorMessage: "error_message",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CommonV3ErrorMeta$ {
  /** @deprecated use `CommonV3ErrorMeta$inboundSchema` instead. */
  export const inboundSchema = CommonV3ErrorMeta$inboundSchema;
  /** @deprecated use `CommonV3ErrorMeta$outboundSchema` instead. */
  export const outboundSchema = CommonV3ErrorMeta$outboundSchema;
  /** @deprecated use `CommonV3ErrorMeta$Outbound` instead. */
  export type Outbound = CommonV3ErrorMeta$Outbound;
}

export function commonV3ErrorMetaToJSON(
  commonV3ErrorMeta: CommonV3ErrorMeta,
): string {
  return JSON.stringify(
    CommonV3ErrorMeta$outboundSchema.parse(commonV3ErrorMeta),
  );
}

export function commonV3ErrorMetaFromJSON(
  jsonString: string,
): SafeParseResult<CommonV3ErrorMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CommonV3ErrorMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CommonV3ErrorMeta' from JSON`,
  );
}
