/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type V3GlobalEventRulesRuleActionUpdate = {
  /**
   * The service ID to which the alert should be routed.
   */
  routeTo?: string | undefined;
};

/** @internal */
export const V3GlobalEventRulesRuleActionUpdate$inboundSchema: z.ZodType<
  V3GlobalEventRulesRuleActionUpdate,
  z.ZodTypeDef,
  unknown
> = z.object({
  route_to: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "route_to": "routeTo",
  });
});

/** @internal */
export type V3GlobalEventRulesRuleActionUpdate$Outbound = {
  route_to?: string | undefined;
};

/** @internal */
export const V3GlobalEventRulesRuleActionUpdate$outboundSchema: z.ZodType<
  V3GlobalEventRulesRuleActionUpdate$Outbound,
  z.ZodTypeDef,
  V3GlobalEventRulesRuleActionUpdate
> = z.object({
  routeTo: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    routeTo: "route_to",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3GlobalEventRulesRuleActionUpdate$ {
  /** @deprecated use `V3GlobalEventRulesRuleActionUpdate$inboundSchema` instead. */
  export const inboundSchema = V3GlobalEventRulesRuleActionUpdate$inboundSchema;
  /** @deprecated use `V3GlobalEventRulesRuleActionUpdate$outboundSchema` instead. */
  export const outboundSchema =
    V3GlobalEventRulesRuleActionUpdate$outboundSchema;
  /** @deprecated use `V3GlobalEventRulesRuleActionUpdate$Outbound` instead. */
  export type Outbound = V3GlobalEventRulesRuleActionUpdate$Outbound;
}

export function v3GlobalEventRulesRuleActionUpdateToJSON(
  v3GlobalEventRulesRuleActionUpdate: V3GlobalEventRulesRuleActionUpdate,
): string {
  return JSON.stringify(
    V3GlobalEventRulesRuleActionUpdate$outboundSchema.parse(
      v3GlobalEventRulesRuleActionUpdate,
    ),
  );
}

export function v3GlobalEventRulesRuleActionUpdateFromJSON(
  jsonString: string,
): SafeParseResult<V3GlobalEventRulesRuleActionUpdate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V3GlobalEventRulesRuleActionUpdate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3GlobalEventRulesRuleActionUpdate' from JSON`,
  );
}
