/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type V3GlobalOncallReminderRulesRule = {
  type: string;
  time: number;
};

/** @internal */
export const V3GlobalOncallReminderRulesRule$inboundSchema: z.ZodType<
  V3GlobalOncallReminderRulesRule,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.string(),
  time: z.number().int(),
});

/** @internal */
export type V3GlobalOncallReminderRulesRule$Outbound = {
  type: string;
  time: number;
};

/** @internal */
export const V3GlobalOncallReminderRulesRule$outboundSchema: z.ZodType<
  V3GlobalOncallReminderRulesRule$Outbound,
  z.ZodTypeDef,
  V3GlobalOncallReminderRulesRule
> = z.object({
  type: z.string(),
  time: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3GlobalOncallReminderRulesRule$ {
  /** @deprecated use `V3GlobalOncallReminderRulesRule$inboundSchema` instead. */
  export const inboundSchema = V3GlobalOncallReminderRulesRule$inboundSchema;
  /** @deprecated use `V3GlobalOncallReminderRulesRule$outboundSchema` instead. */
  export const outboundSchema = V3GlobalOncallReminderRulesRule$outboundSchema;
  /** @deprecated use `V3GlobalOncallReminderRulesRule$Outbound` instead. */
  export type Outbound = V3GlobalOncallReminderRulesRule$Outbound;
}

export function v3GlobalOncallReminderRulesRuleToJSON(
  v3GlobalOncallReminderRulesRule: V3GlobalOncallReminderRulesRule,
): string {
  return JSON.stringify(
    V3GlobalOncallReminderRulesRule$outboundSchema.parse(
      v3GlobalOncallReminderRulesRule,
    ),
  );
}

export function v3GlobalOncallReminderRulesRuleFromJSON(
  jsonString: string,
): SafeParseResult<V3GlobalOncallReminderRulesRule, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3GlobalOncallReminderRulesRule$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3GlobalOncallReminderRulesRule' from JSON`,
  );
}
