/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Represents a relevant people log entry.
 */
export type V3IncidentsTagsRelevantPeopleLog = {
  userId: string;
  actionTaken: string;
  actionTakenBy: string;
  actionTime: Date;
};

/** @internal */
export const V3IncidentsTagsRelevantPeopleLog$inboundSchema: z.ZodType<
  V3IncidentsTagsRelevantPeopleLog,
  z.ZodTypeDef,
  unknown
> = z.object({
  userId: z.string(),
  actionTaken: z.string(),
  actionTakenBy: z.string(),
  actionTime: z.string().datetime({ offset: true }).transform(v => new Date(v)),
});

/** @internal */
export type V3IncidentsTagsRelevantPeopleLog$Outbound = {
  userId: string;
  actionTaken: string;
  actionTakenBy: string;
  actionTime: string;
};

/** @internal */
export const V3IncidentsTagsRelevantPeopleLog$outboundSchema: z.ZodType<
  V3IncidentsTagsRelevantPeopleLog$Outbound,
  z.ZodTypeDef,
  V3IncidentsTagsRelevantPeopleLog
> = z.object({
  userId: z.string(),
  actionTaken: z.string(),
  actionTakenBy: z.string(),
  actionTime: z.date().transform(v => v.toISOString()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3IncidentsTagsRelevantPeopleLog$ {
  /** @deprecated use `V3IncidentsTagsRelevantPeopleLog$inboundSchema` instead. */
  export const inboundSchema = V3IncidentsTagsRelevantPeopleLog$inboundSchema;
  /** @deprecated use `V3IncidentsTagsRelevantPeopleLog$outboundSchema` instead. */
  export const outboundSchema = V3IncidentsTagsRelevantPeopleLog$outboundSchema;
  /** @deprecated use `V3IncidentsTagsRelevantPeopleLog$Outbound` instead. */
  export type Outbound = V3IncidentsTagsRelevantPeopleLog$Outbound;
}

export function v3IncidentsTagsRelevantPeopleLogToJSON(
  v3IncidentsTagsRelevantPeopleLog: V3IncidentsTagsRelevantPeopleLog,
): string {
  return JSON.stringify(
    V3IncidentsTagsRelevantPeopleLog$outboundSchema.parse(
      v3IncidentsTagsRelevantPeopleLog,
    ),
  );
}

export function v3IncidentsTagsRelevantPeopleLogFromJSON(
  jsonString: string,
): SafeParseResult<V3IncidentsTagsRelevantPeopleLog, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3IncidentsTagsRelevantPeopleLog$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3IncidentsTagsRelevantPeopleLog' from JSON`,
  );
}
