/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Represents a communication card.
 */
export type V3IncidentsCommunicationCardsCommunicationCardResponse = {
  createdAt: string;
  updatedAt: string;
  deletedAt?: any | undefined;
  id: number;
  incidentId: string;
  url: string;
  type: string;
  title: string;
  channelId: string;
  archivedAt?: any | undefined;
};

/** @internal */
export const V3IncidentsCommunicationCardsCommunicationCardResponse$inboundSchema:
  z.ZodType<
    V3IncidentsCommunicationCardsCommunicationCardResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    created_at: z.string(),
    updated_at: z.string(),
    deleted_at: z.any().optional(),
    id: z.number().int(),
    incident_id: z.string(),
    url: z.string(),
    type: z.string(),
    title: z.string(),
    channel_id: z.string(),
    archived_at: z.any().optional(),
  }).transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "updated_at": "updatedAt",
      "deleted_at": "deletedAt",
      "incident_id": "incidentId",
      "channel_id": "channelId",
      "archived_at": "archivedAt",
    });
  });

/** @internal */
export type V3IncidentsCommunicationCardsCommunicationCardResponse$Outbound = {
  created_at: string;
  updated_at: string;
  deleted_at?: any | undefined;
  id: number;
  incident_id: string;
  url: string;
  type: string;
  title: string;
  channel_id: string;
  archived_at?: any | undefined;
};

/** @internal */
export const V3IncidentsCommunicationCardsCommunicationCardResponse$outboundSchema:
  z.ZodType<
    V3IncidentsCommunicationCardsCommunicationCardResponse$Outbound,
    z.ZodTypeDef,
    V3IncidentsCommunicationCardsCommunicationCardResponse
  > = z.object({
    createdAt: z.string(),
    updatedAt: z.string(),
    deletedAt: z.any().optional(),
    id: z.number().int(),
    incidentId: z.string(),
    url: z.string(),
    type: z.string(),
    title: z.string(),
    channelId: z.string(),
    archivedAt: z.any().optional(),
  }).transform((v) => {
    return remap$(v, {
      createdAt: "created_at",
      updatedAt: "updated_at",
      deletedAt: "deleted_at",
      incidentId: "incident_id",
      channelId: "channel_id",
      archivedAt: "archived_at",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3IncidentsCommunicationCardsCommunicationCardResponse$ {
  /** @deprecated use `V3IncidentsCommunicationCardsCommunicationCardResponse$inboundSchema` instead. */
  export const inboundSchema =
    V3IncidentsCommunicationCardsCommunicationCardResponse$inboundSchema;
  /** @deprecated use `V3IncidentsCommunicationCardsCommunicationCardResponse$outboundSchema` instead. */
  export const outboundSchema =
    V3IncidentsCommunicationCardsCommunicationCardResponse$outboundSchema;
  /** @deprecated use `V3IncidentsCommunicationCardsCommunicationCardResponse$Outbound` instead. */
  export type Outbound =
    V3IncidentsCommunicationCardsCommunicationCardResponse$Outbound;
}

export function v3IncidentsCommunicationCardsCommunicationCardResponseToJSON(
  v3IncidentsCommunicationCardsCommunicationCardResponse:
    V3IncidentsCommunicationCardsCommunicationCardResponse,
): string {
  return JSON.stringify(
    V3IncidentsCommunicationCardsCommunicationCardResponse$outboundSchema.parse(
      v3IncidentsCommunicationCardsCommunicationCardResponse,
    ),
  );
}

export function v3IncidentsCommunicationCardsCommunicationCardResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  V3IncidentsCommunicationCardsCommunicationCardResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3IncidentsCommunicationCardsCommunicationCardResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'V3IncidentsCommunicationCardsCommunicationCardResponse' from JSON`,
  );
}
