/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Represents a response note in an incident.
 */
export type V3IncidentsResponseNote = {
  timeOfNote: Date;
  note: string;
  userId: string;
};

/** @internal */
export const V3IncidentsResponseNote$inboundSchema: z.ZodType<
  V3IncidentsResponseNote,
  z.ZodTypeDef,
  unknown
> = z.object({
  timeOfNote: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  note: z.string(),
  userId: z.string(),
});

/** @internal */
export type V3IncidentsResponseNote$Outbound = {
  timeOfNote: string;
  note: string;
  userId: string;
};

/** @internal */
export const V3IncidentsResponseNote$outboundSchema: z.ZodType<
  V3IncidentsResponseNote$Outbound,
  z.ZodTypeDef,
  V3IncidentsResponseNote
> = z.object({
  timeOfNote: z.date().transform(v => v.toISOString()),
  note: z.string(),
  userId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3IncidentsResponseNote$ {
  /** @deprecated use `V3IncidentsResponseNote$inboundSchema` instead. */
  export const inboundSchema = V3IncidentsResponseNote$inboundSchema;
  /** @deprecated use `V3IncidentsResponseNote$outboundSchema` instead. */
  export const outboundSchema = V3IncidentsResponseNote$outboundSchema;
  /** @deprecated use `V3IncidentsResponseNote$Outbound` instead. */
  export type Outbound = V3IncidentsResponseNote$Outbound;
}

export function v3IncidentsResponseNoteToJSON(
  v3IncidentsResponseNote: V3IncidentsResponseNote,
): string {
  return JSON.stringify(
    V3IncidentsResponseNote$outboundSchema.parse(v3IncidentsResponseNote),
  );
}

export function v3IncidentsResponseNoteFromJSON(
  jsonString: string,
): SafeParseResult<V3IncidentsResponseNote, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3IncidentsResponseNote$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3IncidentsResponseNote' from JSON`,
  );
}
