/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type V3IncidentsSnoozeNotificationsSnoozeIncidentRequest = {
  snoozeDurationInMins: number;
};

/** @internal */
export const V3IncidentsSnoozeNotificationsSnoozeIncidentRequest$inboundSchema:
  z.ZodType<
    V3IncidentsSnoozeNotificationsSnoozeIncidentRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    snooze_duration_in_mins: z.number().int(),
  }).transform((v) => {
    return remap$(v, {
      "snooze_duration_in_mins": "snoozeDurationInMins",
    });
  });

/** @internal */
export type V3IncidentsSnoozeNotificationsSnoozeIncidentRequest$Outbound = {
  snooze_duration_in_mins: number;
};

/** @internal */
export const V3IncidentsSnoozeNotificationsSnoozeIncidentRequest$outboundSchema:
  z.ZodType<
    V3IncidentsSnoozeNotificationsSnoozeIncidentRequest$Outbound,
    z.ZodTypeDef,
    V3IncidentsSnoozeNotificationsSnoozeIncidentRequest
  > = z.object({
    snoozeDurationInMins: z.number().int(),
  }).transform((v) => {
    return remap$(v, {
      snoozeDurationInMins: "snooze_duration_in_mins",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3IncidentsSnoozeNotificationsSnoozeIncidentRequest$ {
  /** @deprecated use `V3IncidentsSnoozeNotificationsSnoozeIncidentRequest$inboundSchema` instead. */
  export const inboundSchema =
    V3IncidentsSnoozeNotificationsSnoozeIncidentRequest$inboundSchema;
  /** @deprecated use `V3IncidentsSnoozeNotificationsSnoozeIncidentRequest$outboundSchema` instead. */
  export const outboundSchema =
    V3IncidentsSnoozeNotificationsSnoozeIncidentRequest$outboundSchema;
  /** @deprecated use `V3IncidentsSnoozeNotificationsSnoozeIncidentRequest$Outbound` instead. */
  export type Outbound =
    V3IncidentsSnoozeNotificationsSnoozeIncidentRequest$Outbound;
}

export function v3IncidentsSnoozeNotificationsSnoozeIncidentRequestToJSON(
  v3IncidentsSnoozeNotificationsSnoozeIncidentRequest:
    V3IncidentsSnoozeNotificationsSnoozeIncidentRequest,
): string {
  return JSON.stringify(
    V3IncidentsSnoozeNotificationsSnoozeIncidentRequest$outboundSchema.parse(
      v3IncidentsSnoozeNotificationsSnoozeIncidentRequest,
    ),
  );
}

export function v3IncidentsSnoozeNotificationsSnoozeIncidentRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  V3IncidentsSnoozeNotificationsSnoozeIncidentRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3IncidentsSnoozeNotificationsSnoozeIncidentRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V3IncidentsSnoozeNotificationsSnoozeIncidentRequest' from JSON`,
  );
}
