/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type Step = {
  content: string;
  completed: boolean;
  completedAt?: Date | undefined;
};

export type V3IncidentsRunbooksRunbookResponse = {
  id?: string | undefined;
  incidentId: string;
  runbookId: string;
  name: string;
  steps: Array<Step>;
  deleted?: boolean | undefined;
  deletedAt?: Date | undefined;
};

/** @internal */
export const Step$inboundSchema: z.ZodType<Step, z.ZodTypeDef, unknown> = z
  .object({
    content: z.string(),
    completed: z.boolean(),
    completed_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      "completed_at": "completedAt",
    });
  });

/** @internal */
export type Step$Outbound = {
  content: string;
  completed: boolean;
  completed_at?: string | undefined;
};

/** @internal */
export const Step$outboundSchema: z.ZodType<Step$Outbound, z.ZodTypeDef, Step> =
  z.object({
    content: z.string(),
    completed: z.boolean(),
    completedAt: z.date().transform(v => v.toISOString()).optional(),
  }).transform((v) => {
    return remap$(v, {
      completedAt: "completed_at",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Step$ {
  /** @deprecated use `Step$inboundSchema` instead. */
  export const inboundSchema = Step$inboundSchema;
  /** @deprecated use `Step$outboundSchema` instead. */
  export const outboundSchema = Step$outboundSchema;
  /** @deprecated use `Step$Outbound` instead. */
  export type Outbound = Step$Outbound;
}

export function stepToJSON(step: Step): string {
  return JSON.stringify(Step$outboundSchema.parse(step));
}

export function stepFromJSON(
  jsonString: string,
): SafeParseResult<Step, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Step$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Step' from JSON`,
  );
}

/** @internal */
export const V3IncidentsRunbooksRunbookResponse$inboundSchema: z.ZodType<
  V3IncidentsRunbooksRunbookResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  incident_id: z.string(),
  runbook_id: z.string(),
  name: z.string(),
  steps: z.array(z.lazy(() => Step$inboundSchema)),
  deleted: z.boolean().optional(),
  deleted_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "incident_id": "incidentId",
    "runbook_id": "runbookId",
    "deleted_at": "deletedAt",
  });
});

/** @internal */
export type V3IncidentsRunbooksRunbookResponse$Outbound = {
  id?: string | undefined;
  incident_id: string;
  runbook_id: string;
  name: string;
  steps: Array<Step$Outbound>;
  deleted?: boolean | undefined;
  deleted_at?: string | undefined;
};

/** @internal */
export const V3IncidentsRunbooksRunbookResponse$outboundSchema: z.ZodType<
  V3IncidentsRunbooksRunbookResponse$Outbound,
  z.ZodTypeDef,
  V3IncidentsRunbooksRunbookResponse
> = z.object({
  id: z.string().optional(),
  incidentId: z.string(),
  runbookId: z.string(),
  name: z.string(),
  steps: z.array(z.lazy(() => Step$outboundSchema)),
  deleted: z.boolean().optional(),
  deletedAt: z.date().transform(v => v.toISOString()).optional(),
}).transform((v) => {
  return remap$(v, {
    incidentId: "incident_id",
    runbookId: "runbook_id",
    deletedAt: "deleted_at",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3IncidentsRunbooksRunbookResponse$ {
  /** @deprecated use `V3IncidentsRunbooksRunbookResponse$inboundSchema` instead. */
  export const inboundSchema = V3IncidentsRunbooksRunbookResponse$inboundSchema;
  /** @deprecated use `V3IncidentsRunbooksRunbookResponse$outboundSchema` instead. */
  export const outboundSchema =
    V3IncidentsRunbooksRunbookResponse$outboundSchema;
  /** @deprecated use `V3IncidentsRunbooksRunbookResponse$Outbound` instead. */
  export type Outbound = V3IncidentsRunbooksRunbookResponse$Outbound;
}

export function v3IncidentsRunbooksRunbookResponseToJSON(
  v3IncidentsRunbooksRunbookResponse: V3IncidentsRunbooksRunbookResponse,
): string {
  return JSON.stringify(
    V3IncidentsRunbooksRunbookResponse$outboundSchema.parse(
      v3IncidentsRunbooksRunbookResponse,
    ),
  );
}

export function v3IncidentsRunbooksRunbookResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3IncidentsRunbooksRunbookResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V3IncidentsRunbooksRunbookResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3IncidentsRunbooksRunbookResponse' from JSON`,
  );
}
