/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Defines the format of the export.
 */
export const V3IncidentsExportFormat = {
  Json: "json",
  Csv: "csv",
} as const;
/**
 * Defines the format of the export.
 */
export type V3IncidentsExportFormat = ClosedEnum<
  typeof V3IncidentsExportFormat
>;

/** @internal */
export const V3IncidentsExportFormat$inboundSchema: z.ZodNativeEnum<
  typeof V3IncidentsExportFormat
> = z.nativeEnum(V3IncidentsExportFormat);

/** @internal */
export const V3IncidentsExportFormat$outboundSchema: z.ZodNativeEnum<
  typeof V3IncidentsExportFormat
> = V3IncidentsExportFormat$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3IncidentsExportFormat$ {
  /** @deprecated use `V3IncidentsExportFormat$inboundSchema` instead. */
  export const inboundSchema = V3IncidentsExportFormat$inboundSchema;
  /** @deprecated use `V3IncidentsExportFormat$outboundSchema` instead. */
  export const outboundSchema = V3IncidentsExportFormat$outboundSchema;
}
