/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  CommonV3EntityOwner,
  CommonV3EntityOwner$inboundSchema,
  CommonV3EntityOwner$Outbound,
  CommonV3EntityOwner$outboundSchema,
} from "./commonv3entityowner.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  V3RunbooksStep,
  V3RunbooksStep$inboundSchema,
  V3RunbooksStep$Outbound,
  V3RunbooksStep$outboundSchema,
} from "./v3runbooksstep.js";

/**
 * Represents the request body for updating a runbook.
 */
export type V3RunbooksUpdateRunbookRequest = {
  /**
   * The name of the runbook.
   */
  name: string;
  /**
   * The steps that make up the runbook.
   */
  steps: Array<V3RunbooksStep>;
  /**
   * The owner of the entity.
   */
  entityOwner?: CommonV3EntityOwner | undefined;
};

/** @internal */
export const V3RunbooksUpdateRunbookRequest$inboundSchema: z.ZodType<
  V3RunbooksUpdateRunbookRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  steps: z.array(V3RunbooksStep$inboundSchema),
  entity_owner: CommonV3EntityOwner$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "entity_owner": "entityOwner",
  });
});

/** @internal */
export type V3RunbooksUpdateRunbookRequest$Outbound = {
  name: string;
  steps: Array<V3RunbooksStep$Outbound>;
  entity_owner?: CommonV3EntityOwner$Outbound | undefined;
};

/** @internal */
export const V3RunbooksUpdateRunbookRequest$outboundSchema: z.ZodType<
  V3RunbooksUpdateRunbookRequest$Outbound,
  z.ZodTypeDef,
  V3RunbooksUpdateRunbookRequest
> = z.object({
  name: z.string(),
  steps: z.array(V3RunbooksStep$outboundSchema),
  entityOwner: CommonV3EntityOwner$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    entityOwner: "entity_owner",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3RunbooksUpdateRunbookRequest$ {
  /** @deprecated use `V3RunbooksUpdateRunbookRequest$inboundSchema` instead. */
  export const inboundSchema = V3RunbooksUpdateRunbookRequest$inboundSchema;
  /** @deprecated use `V3RunbooksUpdateRunbookRequest$outboundSchema` instead. */
  export const outboundSchema = V3RunbooksUpdateRunbookRequest$outboundSchema;
  /** @deprecated use `V3RunbooksUpdateRunbookRequest$Outbound` instead. */
  export type Outbound = V3RunbooksUpdateRunbookRequest$Outbound;
}

export function v3RunbooksUpdateRunbookRequestToJSON(
  v3RunbooksUpdateRunbookRequest: V3RunbooksUpdateRunbookRequest,
): string {
  return JSON.stringify(
    V3RunbooksUpdateRunbookRequest$outboundSchema.parse(
      v3RunbooksUpdateRunbookRequest,
    ),
  );
}

export function v3RunbooksUpdateRunbookRequestFromJSON(
  jsonString: string,
): SafeParseResult<V3RunbooksUpdateRunbookRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3RunbooksUpdateRunbookRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3RunbooksUpdateRunbookRequest' from JSON`,
  );
}
