/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  CommonV3EntityOwner,
  CommonV3EntityOwner$inboundSchema,
  CommonV3EntityOwner$Outbound,
  CommonV3EntityOwner$outboundSchema,
} from "./commonv3entityowner.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  V3RunbooksStep,
  V3RunbooksStep$inboundSchema,
  V3RunbooksStep$Outbound,
  V3RunbooksStep$outboundSchema,
} from "./v3runbooksstep.js";

/**
 * Represents the request body for creating a new runbook.
 */
export type V3RunbooksCreateRunbookRequest = {
  /**
   * The name of the runbook.
   */
  name: string;
  /**
   * The steps that make up the runbook.
   */
  steps: Array<V3RunbooksStep>;
  /**
   * The ID of the team that owns this runbook.
   */
  ownerId: string;
  /**
   * The owner of the entity.
   */
  entityOwner?: CommonV3EntityOwner | undefined;
};

/** @internal */
export const V3RunbooksCreateRunbookRequest$inboundSchema: z.ZodType<
  V3RunbooksCreateRunbookRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  steps: z.array(V3RunbooksStep$inboundSchema),
  owner_id: z.string(),
  entity_owner: CommonV3EntityOwner$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "owner_id": "ownerId",
    "entity_owner": "entityOwner",
  });
});

/** @internal */
export type V3RunbooksCreateRunbookRequest$Outbound = {
  name: string;
  steps: Array<V3RunbooksStep$Outbound>;
  owner_id: string;
  entity_owner?: CommonV3EntityOwner$Outbound | undefined;
};

/** @internal */
export const V3RunbooksCreateRunbookRequest$outboundSchema: z.ZodType<
  V3RunbooksCreateRunbookRequest$Outbound,
  z.ZodTypeDef,
  V3RunbooksCreateRunbookRequest
> = z.object({
  name: z.string(),
  steps: z.array(V3RunbooksStep$outboundSchema),
  ownerId: z.string(),
  entityOwner: CommonV3EntityOwner$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    ownerId: "owner_id",
    entityOwner: "entity_owner",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3RunbooksCreateRunbookRequest$ {
  /** @deprecated use `V3RunbooksCreateRunbookRequest$inboundSchema` instead. */
  export const inboundSchema = V3RunbooksCreateRunbookRequest$inboundSchema;
  /** @deprecated use `V3RunbooksCreateRunbookRequest$outboundSchema` instead. */
  export const outboundSchema = V3RunbooksCreateRunbookRequest$outboundSchema;
  /** @deprecated use `V3RunbooksCreateRunbookRequest$Outbound` instead. */
  export type Outbound = V3RunbooksCreateRunbookRequest$Outbound;
}

export function v3RunbooksCreateRunbookRequestToJSON(
  v3RunbooksCreateRunbookRequest: V3RunbooksCreateRunbookRequest,
): string {
  return JSON.stringify(
    V3RunbooksCreateRunbookRequest$outboundSchema.parse(
      v3RunbooksCreateRunbookRequest,
    ),
  );
}

export function v3RunbooksCreateRunbookRequestFromJSON(
  jsonString: string,
): SafeParseResult<V3RunbooksCreateRunbookRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3RunbooksCreateRunbookRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3RunbooksCreateRunbookRequest' from JSON`,
  );
}
