/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  V3ServicesSuppressionRulesSuppressionRule,
  V3ServicesSuppressionRulesSuppressionRule$inboundSchema,
  V3ServicesSuppressionRulesSuppressionRule$Outbound,
  V3ServicesSuppressionRulesSuppressionRule$outboundSchema,
} from "./v3servicessuppressionrulessuppressionrule.js";

export type V3ServicesSuppressionRulesCreateOrUpdateSuppressionRulesRequest = {
  rules: Array<V3ServicesSuppressionRulesSuppressionRule>;
};

/** @internal */
export const V3ServicesSuppressionRulesCreateOrUpdateSuppressionRulesRequest$inboundSchema:
  z.ZodType<
    V3ServicesSuppressionRulesCreateOrUpdateSuppressionRulesRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    rules: z.array(V3ServicesSuppressionRulesSuppressionRule$inboundSchema),
  });

/** @internal */
export type V3ServicesSuppressionRulesCreateOrUpdateSuppressionRulesRequest$Outbound =
  {
    rules: Array<V3ServicesSuppressionRulesSuppressionRule$Outbound>;
  };

/** @internal */
export const V3ServicesSuppressionRulesCreateOrUpdateSuppressionRulesRequest$outboundSchema:
  z.ZodType<
    V3ServicesSuppressionRulesCreateOrUpdateSuppressionRulesRequest$Outbound,
    z.ZodTypeDef,
    V3ServicesSuppressionRulesCreateOrUpdateSuppressionRulesRequest
  > = z.object({
    rules: z.array(V3ServicesSuppressionRulesSuppressionRule$outboundSchema),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3ServicesSuppressionRulesCreateOrUpdateSuppressionRulesRequest$ {
  /** @deprecated use `V3ServicesSuppressionRulesCreateOrUpdateSuppressionRulesRequest$inboundSchema` instead. */
  export const inboundSchema =
    V3ServicesSuppressionRulesCreateOrUpdateSuppressionRulesRequest$inboundSchema;
  /** @deprecated use `V3ServicesSuppressionRulesCreateOrUpdateSuppressionRulesRequest$outboundSchema` instead. */
  export const outboundSchema =
    V3ServicesSuppressionRulesCreateOrUpdateSuppressionRulesRequest$outboundSchema;
  /** @deprecated use `V3ServicesSuppressionRulesCreateOrUpdateSuppressionRulesRequest$Outbound` instead. */
  export type Outbound =
    V3ServicesSuppressionRulesCreateOrUpdateSuppressionRulesRequest$Outbound;
}

export function v3ServicesSuppressionRulesCreateOrUpdateSuppressionRulesRequestToJSON(
  v3ServicesSuppressionRulesCreateOrUpdateSuppressionRulesRequest:
    V3ServicesSuppressionRulesCreateOrUpdateSuppressionRulesRequest,
): string {
  return JSON.stringify(
    V3ServicesSuppressionRulesCreateOrUpdateSuppressionRulesRequest$outboundSchema
      .parse(v3ServicesSuppressionRulesCreateOrUpdateSuppressionRulesRequest),
  );
}

export function v3ServicesSuppressionRulesCreateOrUpdateSuppressionRulesRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  V3ServicesSuppressionRulesCreateOrUpdateSuppressionRulesRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3ServicesSuppressionRulesCreateOrUpdateSuppressionRulesRequest$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'V3ServicesSuppressionRulesCreateOrUpdateSuppressionRulesRequest' from JSON`,
  );
}
