/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  V3ServicesJiraIssueType,
  V3ServicesJiraIssueType$inboundSchema,
  V3ServicesJiraIssueType$Outbound,
  V3ServicesJiraIssueType$outboundSchema,
} from "./v3servicesjiraissuetype.js";
import {
  V3ServicesJiraProject,
  V3ServicesJiraProject$inboundSchema,
  V3ServicesJiraProject$Outbound,
  V3ServicesJiraProject$outboundSchema,
} from "./v3servicesjiraproject.js";
import {
  V3ServicesJiraStatusMap,
  V3ServicesJiraStatusMap$inboundSchema,
  V3ServicesJiraStatusMap$Outbound,
  V3ServicesJiraStatusMap$outboundSchema,
} from "./v3servicesjirastatusmap.js";

export type V3ServicesJiraCloudExtension = {
  jiraClientKey: string;
  project: V3ServicesJiraProject;
  issueType: V3ServicesJiraIssueType;
  statusmaps?: Array<V3ServicesJiraStatusMap> | null | undefined;
  isManual: boolean;
};

/** @internal */
export const V3ServicesJiraCloudExtension$inboundSchema: z.ZodType<
  V3ServicesJiraCloudExtension,
  z.ZodTypeDef,
  unknown
> = z.object({
  jira_client_key: z.string(),
  project: V3ServicesJiraProject$inboundSchema,
  issue_type: V3ServicesJiraIssueType$inboundSchema,
  statusmaps: z.nullable(z.array(V3ServicesJiraStatusMap$inboundSchema))
    .optional(),
  is_manual: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    "jira_client_key": "jiraClientKey",
    "issue_type": "issueType",
    "is_manual": "isManual",
  });
});

/** @internal */
export type V3ServicesJiraCloudExtension$Outbound = {
  jira_client_key: string;
  project: V3ServicesJiraProject$Outbound;
  issue_type: V3ServicesJiraIssueType$Outbound;
  statusmaps?: Array<V3ServicesJiraStatusMap$Outbound> | null | undefined;
  is_manual: boolean;
};

/** @internal */
export const V3ServicesJiraCloudExtension$outboundSchema: z.ZodType<
  V3ServicesJiraCloudExtension$Outbound,
  z.ZodTypeDef,
  V3ServicesJiraCloudExtension
> = z.object({
  jiraClientKey: z.string(),
  project: V3ServicesJiraProject$outboundSchema,
  issueType: V3ServicesJiraIssueType$outboundSchema,
  statusmaps: z.nullable(z.array(V3ServicesJiraStatusMap$outboundSchema))
    .optional(),
  isManual: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    jiraClientKey: "jira_client_key",
    issueType: "issue_type",
    isManual: "is_manual",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3ServicesJiraCloudExtension$ {
  /** @deprecated use `V3ServicesJiraCloudExtension$inboundSchema` instead. */
  export const inboundSchema = V3ServicesJiraCloudExtension$inboundSchema;
  /** @deprecated use `V3ServicesJiraCloudExtension$outboundSchema` instead. */
  export const outboundSchema = V3ServicesJiraCloudExtension$outboundSchema;
  /** @deprecated use `V3ServicesJiraCloudExtension$Outbound` instead. */
  export type Outbound = V3ServicesJiraCloudExtension$Outbound;
}

export function v3ServicesJiraCloudExtensionToJSON(
  v3ServicesJiraCloudExtension: V3ServicesJiraCloudExtension,
): string {
  return JSON.stringify(
    V3ServicesJiraCloudExtension$outboundSchema.parse(
      v3ServicesJiraCloudExtension,
    ),
  );
}

export function v3ServicesJiraCloudExtensionFromJSON(
  jsonString: string,
): SafeParseResult<V3ServicesJiraCloudExtension, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3ServicesJiraCloudExtension$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3ServicesJiraCloudExtension' from JSON`,
  );
}
