/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type V3ServicesAPTAConfigRequest = {
  isEnabled: boolean;
  timeoutInMins: number;
};

/** @internal */
export const V3ServicesAPTAConfigRequest$inboundSchema: z.ZodType<
  V3ServicesAPTAConfigRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  is_enabled: z.boolean(),
  timeout_in_mins: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "is_enabled": "isEnabled",
    "timeout_in_mins": "timeoutInMins",
  });
});

/** @internal */
export type V3ServicesAPTAConfigRequest$Outbound = {
  is_enabled: boolean;
  timeout_in_mins: number;
};

/** @internal */
export const V3ServicesAPTAConfigRequest$outboundSchema: z.ZodType<
  V3ServicesAPTAConfigRequest$Outbound,
  z.ZodTypeDef,
  V3ServicesAPTAConfigRequest
> = z.object({
  isEnabled: z.boolean(),
  timeoutInMins: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    isEnabled: "is_enabled",
    timeoutInMins: "timeout_in_mins",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3ServicesAPTAConfigRequest$ {
  /** @deprecated use `V3ServicesAPTAConfigRequest$inboundSchema` instead. */
  export const inboundSchema = V3ServicesAPTAConfigRequest$inboundSchema;
  /** @deprecated use `V3ServicesAPTAConfigRequest$outboundSchema` instead. */
  export const outboundSchema = V3ServicesAPTAConfigRequest$outboundSchema;
  /** @deprecated use `V3ServicesAPTAConfigRequest$Outbound` instead. */
  export type Outbound = V3ServicesAPTAConfigRequest$Outbound;
}

export function v3ServicesAPTAConfigRequestToJSON(
  v3ServicesAPTAConfigRequest: V3ServicesAPTAConfigRequest,
): string {
  return JSON.stringify(
    V3ServicesAPTAConfigRequest$outboundSchema.parse(
      v3ServicesAPTAConfigRequest,
    ),
  );
}

export function v3ServicesAPTAConfigRequestFromJSON(
  jsonString: string,
): SafeParseResult<V3ServicesAPTAConfigRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3ServicesAPTAConfigRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3ServicesAPTAConfigRequest' from JSON`,
  );
}
