/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type V3ServicesMaintenanceModeMaintenanceModeResponse = {
  serviceId: string;
  maintenanceFrom: Date;
  maintenanceTill: Date;
  repetitionDaily: boolean;
  repetitionWeekly: boolean;
  repetitionTwoWeekly: boolean;
  repetitionThreeWeekly: boolean;
  repetitionMonthly: boolean;
  deleted: boolean;
  repeatTill: Date;
};

/** @internal */
export const V3ServicesMaintenanceModeMaintenanceModeResponse$inboundSchema:
  z.ZodType<
    V3ServicesMaintenanceModeMaintenanceModeResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    service_id: z.string(),
    maintenance_from: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    maintenance_till: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    repetition_daily: z.boolean(),
    repetition_weekly: z.boolean(),
    repetition_two_weekly: z.boolean(),
    repetition_three_weekly: z.boolean(),
    repetition_monthly: z.boolean(),
    deleted: z.boolean(),
    repeat_till: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
  }).transform((v) => {
    return remap$(v, {
      "service_id": "serviceId",
      "maintenance_from": "maintenanceFrom",
      "maintenance_till": "maintenanceTill",
      "repetition_daily": "repetitionDaily",
      "repetition_weekly": "repetitionWeekly",
      "repetition_two_weekly": "repetitionTwoWeekly",
      "repetition_three_weekly": "repetitionThreeWeekly",
      "repetition_monthly": "repetitionMonthly",
      "repeat_till": "repeatTill",
    });
  });

/** @internal */
export type V3ServicesMaintenanceModeMaintenanceModeResponse$Outbound = {
  service_id: string;
  maintenance_from: string;
  maintenance_till: string;
  repetition_daily: boolean;
  repetition_weekly: boolean;
  repetition_two_weekly: boolean;
  repetition_three_weekly: boolean;
  repetition_monthly: boolean;
  deleted: boolean;
  repeat_till: string;
};

/** @internal */
export const V3ServicesMaintenanceModeMaintenanceModeResponse$outboundSchema:
  z.ZodType<
    V3ServicesMaintenanceModeMaintenanceModeResponse$Outbound,
    z.ZodTypeDef,
    V3ServicesMaintenanceModeMaintenanceModeResponse
  > = z.object({
    serviceId: z.string(),
    maintenanceFrom: z.date().transform(v => v.toISOString()),
    maintenanceTill: z.date().transform(v => v.toISOString()),
    repetitionDaily: z.boolean(),
    repetitionWeekly: z.boolean(),
    repetitionTwoWeekly: z.boolean(),
    repetitionThreeWeekly: z.boolean(),
    repetitionMonthly: z.boolean(),
    deleted: z.boolean(),
    repeatTill: z.date().transform(v => v.toISOString()),
  }).transform((v) => {
    return remap$(v, {
      serviceId: "service_id",
      maintenanceFrom: "maintenance_from",
      maintenanceTill: "maintenance_till",
      repetitionDaily: "repetition_daily",
      repetitionWeekly: "repetition_weekly",
      repetitionTwoWeekly: "repetition_two_weekly",
      repetitionThreeWeekly: "repetition_three_weekly",
      repetitionMonthly: "repetition_monthly",
      repeatTill: "repeat_till",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3ServicesMaintenanceModeMaintenanceModeResponse$ {
  /** @deprecated use `V3ServicesMaintenanceModeMaintenanceModeResponse$inboundSchema` instead. */
  export const inboundSchema =
    V3ServicesMaintenanceModeMaintenanceModeResponse$inboundSchema;
  /** @deprecated use `V3ServicesMaintenanceModeMaintenanceModeResponse$outboundSchema` instead. */
  export const outboundSchema =
    V3ServicesMaintenanceModeMaintenanceModeResponse$outboundSchema;
  /** @deprecated use `V3ServicesMaintenanceModeMaintenanceModeResponse$Outbound` instead. */
  export type Outbound =
    V3ServicesMaintenanceModeMaintenanceModeResponse$Outbound;
}

export function v3ServicesMaintenanceModeMaintenanceModeResponseToJSON(
  v3ServicesMaintenanceModeMaintenanceModeResponse:
    V3ServicesMaintenanceModeMaintenanceModeResponse,
): string {
  return JSON.stringify(
    V3ServicesMaintenanceModeMaintenanceModeResponse$outboundSchema.parse(
      v3ServicesMaintenanceModeMaintenanceModeResponse,
    ),
  );
}

export function v3ServicesMaintenanceModeMaintenanceModeResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  V3ServicesMaintenanceModeMaintenanceModeResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3ServicesMaintenanceModeMaintenanceModeResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V3ServicesMaintenanceModeMaintenanceModeResponse' from JSON`,
  );
}
