/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type V3SLOMarkSLOAffectedRequest = {
  incidentId: string;
  slis: Array<string>;
  errorBudgetSpent: number;
  ownerType: string;
  ownerId: string;
  orgId: string;
};

/** @internal */
export const V3SLOMarkSLOAffectedRequest$inboundSchema: z.ZodType<
  V3SLOMarkSLOAffectedRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  incident_id: z.string(),
  slis: z.array(z.string()),
  error_budget_spent: z.number(),
  owner_type: z.string(),
  owner_id: z.string(),
  org_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "incident_id": "incidentId",
    "error_budget_spent": "errorBudgetSpent",
    "owner_type": "ownerType",
    "owner_id": "ownerId",
    "org_id": "orgId",
  });
});

/** @internal */
export type V3SLOMarkSLOAffectedRequest$Outbound = {
  incident_id: string;
  slis: Array<string>;
  error_budget_spent: number;
  owner_type: string;
  owner_id: string;
  org_id: string;
};

/** @internal */
export const V3SLOMarkSLOAffectedRequest$outboundSchema: z.ZodType<
  V3SLOMarkSLOAffectedRequest$Outbound,
  z.ZodTypeDef,
  V3SLOMarkSLOAffectedRequest
> = z.object({
  incidentId: z.string(),
  slis: z.array(z.string()),
  errorBudgetSpent: z.number(),
  ownerType: z.string(),
  ownerId: z.string(),
  orgId: z.string(),
}).transform((v) => {
  return remap$(v, {
    incidentId: "incident_id",
    errorBudgetSpent: "error_budget_spent",
    ownerType: "owner_type",
    ownerId: "owner_id",
    orgId: "org_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3SLOMarkSLOAffectedRequest$ {
  /** @deprecated use `V3SLOMarkSLOAffectedRequest$inboundSchema` instead. */
  export const inboundSchema = V3SLOMarkSLOAffectedRequest$inboundSchema;
  /** @deprecated use `V3SLOMarkSLOAffectedRequest$outboundSchema` instead. */
  export const outboundSchema = V3SLOMarkSLOAffectedRequest$outboundSchema;
  /** @deprecated use `V3SLOMarkSLOAffectedRequest$Outbound` instead. */
  export type Outbound = V3SLOMarkSLOAffectedRequest$Outbound;
}

export function v3SLOMarkSLOAffectedRequestToJSON(
  v3SLOMarkSLOAffectedRequest: V3SLOMarkSLOAffectedRequest,
): string {
  return JSON.stringify(
    V3SLOMarkSLOAffectedRequest$outboundSchema.parse(
      v3SLOMarkSLOAffectedRequest,
    ),
  );
}

export function v3SLOMarkSLOAffectedRequestFromJSON(
  jsonString: string,
): SafeParseResult<V3SLOMarkSLOAffectedRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3SLOMarkSLOAffectedRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3SLOMarkSLOAffectedRequest' from JSON`,
  );
}
