/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  V3TeamsTeamMember,
  V3TeamsTeamMember$inboundSchema,
  V3TeamsTeamMember$Outbound,
  V3TeamsTeamMember$outboundSchema,
} from "./v3teamsteammember.js";
import {
  V3TeamsTeamRole,
  V3TeamsTeamRole$inboundSchema,
  V3TeamsTeamRole$Outbound,
  V3TeamsTeamRole$outboundSchema,
} from "./v3teamsteamrole.js";

export type V3TeamsTeamBaseResponse = {
  id: string;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  organizationId: string;
  name: string;
  description: string;
  slug: string;
  members: Array<V3TeamsTeamMember>;
  roles: Array<V3TeamsTeamRole>;
  default: boolean;
};

/** @internal */
export const V3TeamsTeamBaseResponse$inboundSchema: z.ZodType<
  V3TeamsTeamBaseResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  created_at: z.string(),
  updated_at: z.string(),
  created_by: z.string(),
  organization_id: z.string(),
  name: z.string(),
  description: z.string(),
  slug: z.string(),
  members: z.array(V3TeamsTeamMember$inboundSchema),
  roles: z.array(V3TeamsTeamRole$inboundSchema),
  default: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "updated_at": "updatedAt",
    "created_by": "createdBy",
    "organization_id": "organizationId",
  });
});

/** @internal */
export type V3TeamsTeamBaseResponse$Outbound = {
  id: string;
  created_at: string;
  updated_at: string;
  created_by: string;
  organization_id: string;
  name: string;
  description: string;
  slug: string;
  members: Array<V3TeamsTeamMember$Outbound>;
  roles: Array<V3TeamsTeamRole$Outbound>;
  default: boolean;
};

/** @internal */
export const V3TeamsTeamBaseResponse$outboundSchema: z.ZodType<
  V3TeamsTeamBaseResponse$Outbound,
  z.ZodTypeDef,
  V3TeamsTeamBaseResponse
> = z.object({
  id: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  createdBy: z.string(),
  organizationId: z.string(),
  name: z.string(),
  description: z.string(),
  slug: z.string(),
  members: z.array(V3TeamsTeamMember$outboundSchema),
  roles: z.array(V3TeamsTeamRole$outboundSchema),
  default: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
    updatedAt: "updated_at",
    createdBy: "created_by",
    organizationId: "organization_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3TeamsTeamBaseResponse$ {
  /** @deprecated use `V3TeamsTeamBaseResponse$inboundSchema` instead. */
  export const inboundSchema = V3TeamsTeamBaseResponse$inboundSchema;
  /** @deprecated use `V3TeamsTeamBaseResponse$outboundSchema` instead. */
  export const outboundSchema = V3TeamsTeamBaseResponse$outboundSchema;
  /** @deprecated use `V3TeamsTeamBaseResponse$Outbound` instead. */
  export type Outbound = V3TeamsTeamBaseResponse$Outbound;
}

export function v3TeamsTeamBaseResponseToJSON(
  v3TeamsTeamBaseResponse: V3TeamsTeamBaseResponse,
): string {
  return JSON.stringify(
    V3TeamsTeamBaseResponse$outboundSchema.parse(v3TeamsTeamBaseResponse),
  );
}

export function v3TeamsTeamBaseResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3TeamsTeamBaseResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3TeamsTeamBaseResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3TeamsTeamBaseResponse' from JSON`,
  );
}
