/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const V3UsersUpdateUserRequestRole = {
  AccountOwner: "account_owner",
  User: "user",
  Stakeholder: "stakeholder",
} as const;
export type V3UsersUpdateUserRequestRole = ClosedEnum<
  typeof V3UsersUpdateUserRequestRole
>;

export type V3UsersUpdateUserRequest = {
  role: V3UsersUpdateUserRequestRole;
};

/** @internal */
export const V3UsersUpdateUserRequestRole$inboundSchema: z.ZodNativeEnum<
  typeof V3UsersUpdateUserRequestRole
> = z.nativeEnum(V3UsersUpdateUserRequestRole);

/** @internal */
export const V3UsersUpdateUserRequestRole$outboundSchema: z.ZodNativeEnum<
  typeof V3UsersUpdateUserRequestRole
> = V3UsersUpdateUserRequestRole$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3UsersUpdateUserRequestRole$ {
  /** @deprecated use `V3UsersUpdateUserRequestRole$inboundSchema` instead. */
  export const inboundSchema = V3UsersUpdateUserRequestRole$inboundSchema;
  /** @deprecated use `V3UsersUpdateUserRequestRole$outboundSchema` instead. */
  export const outboundSchema = V3UsersUpdateUserRequestRole$outboundSchema;
}

/** @internal */
export const V3UsersUpdateUserRequest$inboundSchema: z.ZodType<
  V3UsersUpdateUserRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  role: V3UsersUpdateUserRequestRole$inboundSchema,
});

/** @internal */
export type V3UsersUpdateUserRequest$Outbound = {
  role: string;
};

/** @internal */
export const V3UsersUpdateUserRequest$outboundSchema: z.ZodType<
  V3UsersUpdateUserRequest$Outbound,
  z.ZodTypeDef,
  V3UsersUpdateUserRequest
> = z.object({
  role: V3UsersUpdateUserRequestRole$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3UsersUpdateUserRequest$ {
  /** @deprecated use `V3UsersUpdateUserRequest$inboundSchema` instead. */
  export const inboundSchema = V3UsersUpdateUserRequest$inboundSchema;
  /** @deprecated use `V3UsersUpdateUserRequest$outboundSchema` instead. */
  export const outboundSchema = V3UsersUpdateUserRequest$outboundSchema;
  /** @deprecated use `V3UsersUpdateUserRequest$Outbound` instead. */
  export type Outbound = V3UsersUpdateUserRequest$Outbound;
}

export function v3UsersUpdateUserRequestToJSON(
  v3UsersUpdateUserRequest: V3UsersUpdateUserRequest,
): string {
  return JSON.stringify(
    V3UsersUpdateUserRequest$outboundSchema.parse(v3UsersUpdateUserRequest),
  );
}

export function v3UsersUpdateUserRequestFromJSON(
  jsonString: string,
): SafeParseResult<V3UsersUpdateUserRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3UsersUpdateUserRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3UsersUpdateUserRequest' from JSON`,
  );
}
