/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const V3WorkflowsSqTriggerManualWebhookName = {
  SqTriggerManualWebhook: "sq_trigger_manual_webhook",
} as const;
export type V3WorkflowsSqTriggerManualWebhookName = ClosedEnum<
  typeof V3WorkflowsSqTriggerManualWebhookName
>;

export type V3WorkflowsSqTriggerManualWebhookData = {
  id: string;
};

export type V3WorkflowsSqTriggerManualWebhook = {
  name: V3WorkflowsSqTriggerManualWebhookName;
  data: V3WorkflowsSqTriggerManualWebhookData;
};

/** @internal */
export const V3WorkflowsSqTriggerManualWebhookName$inboundSchema:
  z.ZodNativeEnum<typeof V3WorkflowsSqTriggerManualWebhookName> = z.nativeEnum(
    V3WorkflowsSqTriggerManualWebhookName,
  );

/** @internal */
export const V3WorkflowsSqTriggerManualWebhookName$outboundSchema:
  z.ZodNativeEnum<typeof V3WorkflowsSqTriggerManualWebhookName> =
    V3WorkflowsSqTriggerManualWebhookName$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3WorkflowsSqTriggerManualWebhookName$ {
  /** @deprecated use `V3WorkflowsSqTriggerManualWebhookName$inboundSchema` instead. */
  export const inboundSchema =
    V3WorkflowsSqTriggerManualWebhookName$inboundSchema;
  /** @deprecated use `V3WorkflowsSqTriggerManualWebhookName$outboundSchema` instead. */
  export const outboundSchema =
    V3WorkflowsSqTriggerManualWebhookName$outboundSchema;
}

/** @internal */
export const V3WorkflowsSqTriggerManualWebhookData$inboundSchema: z.ZodType<
  V3WorkflowsSqTriggerManualWebhookData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type V3WorkflowsSqTriggerManualWebhookData$Outbound = {
  id: string;
};

/** @internal */
export const V3WorkflowsSqTriggerManualWebhookData$outboundSchema: z.ZodType<
  V3WorkflowsSqTriggerManualWebhookData$Outbound,
  z.ZodTypeDef,
  V3WorkflowsSqTriggerManualWebhookData
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3WorkflowsSqTriggerManualWebhookData$ {
  /** @deprecated use `V3WorkflowsSqTriggerManualWebhookData$inboundSchema` instead. */
  export const inboundSchema =
    V3WorkflowsSqTriggerManualWebhookData$inboundSchema;
  /** @deprecated use `V3WorkflowsSqTriggerManualWebhookData$outboundSchema` instead. */
  export const outboundSchema =
    V3WorkflowsSqTriggerManualWebhookData$outboundSchema;
  /** @deprecated use `V3WorkflowsSqTriggerManualWebhookData$Outbound` instead. */
  export type Outbound = V3WorkflowsSqTriggerManualWebhookData$Outbound;
}

export function v3WorkflowsSqTriggerManualWebhookDataToJSON(
  v3WorkflowsSqTriggerManualWebhookData: V3WorkflowsSqTriggerManualWebhookData,
): string {
  return JSON.stringify(
    V3WorkflowsSqTriggerManualWebhookData$outboundSchema.parse(
      v3WorkflowsSqTriggerManualWebhookData,
    ),
  );
}

export function v3WorkflowsSqTriggerManualWebhookDataFromJSON(
  jsonString: string,
): SafeParseResult<V3WorkflowsSqTriggerManualWebhookData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V3WorkflowsSqTriggerManualWebhookData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3WorkflowsSqTriggerManualWebhookData' from JSON`,
  );
}

/** @internal */
export const V3WorkflowsSqTriggerManualWebhook$inboundSchema: z.ZodType<
  V3WorkflowsSqTriggerManualWebhook,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: V3WorkflowsSqTriggerManualWebhookName$inboundSchema,
  data: z.lazy(() => V3WorkflowsSqTriggerManualWebhookData$inboundSchema),
});

/** @internal */
export type V3WorkflowsSqTriggerManualWebhook$Outbound = {
  name: string;
  data: V3WorkflowsSqTriggerManualWebhookData$Outbound;
};

/** @internal */
export const V3WorkflowsSqTriggerManualWebhook$outboundSchema: z.ZodType<
  V3WorkflowsSqTriggerManualWebhook$Outbound,
  z.ZodTypeDef,
  V3WorkflowsSqTriggerManualWebhook
> = z.object({
  name: V3WorkflowsSqTriggerManualWebhookName$outboundSchema,
  data: z.lazy(() => V3WorkflowsSqTriggerManualWebhookData$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3WorkflowsSqTriggerManualWebhook$ {
  /** @deprecated use `V3WorkflowsSqTriggerManualWebhook$inboundSchema` instead. */
  export const inboundSchema = V3WorkflowsSqTriggerManualWebhook$inboundSchema;
  /** @deprecated use `V3WorkflowsSqTriggerManualWebhook$outboundSchema` instead. */
  export const outboundSchema =
    V3WorkflowsSqTriggerManualWebhook$outboundSchema;
  /** @deprecated use `V3WorkflowsSqTriggerManualWebhook$Outbound` instead. */
  export type Outbound = V3WorkflowsSqTriggerManualWebhook$Outbound;
}

export function v3WorkflowsSqTriggerManualWebhookToJSON(
  v3WorkflowsSqTriggerManualWebhook: V3WorkflowsSqTriggerManualWebhook,
): string {
  return JSON.stringify(
    V3WorkflowsSqTriggerManualWebhook$outboundSchema.parse(
      v3WorkflowsSqTriggerManualWebhook,
    ),
  );
}

export function v3WorkflowsSqTriggerManualWebhookFromJSON(
  jsonString: string,
): SafeParseResult<V3WorkflowsSqTriggerManualWebhook, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3WorkflowsSqTriggerManualWebhook$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3WorkflowsSqTriggerManualWebhook' from JSON`,
  );
}
