/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const V3WorkflowsSlackArchiveChannelName = {
  SlackArchiveChannel: "slack_archive_channel",
} as const;
export type V3WorkflowsSlackArchiveChannelName = ClosedEnum<
  typeof V3WorkflowsSlackArchiveChannelName
>;

export type V3WorkflowsSlackArchiveChannel = {
  name: V3WorkflowsSlackArchiveChannelName;
};

/** @internal */
export const V3WorkflowsSlackArchiveChannelName$inboundSchema: z.ZodNativeEnum<
  typeof V3WorkflowsSlackArchiveChannelName
> = z.nativeEnum(V3WorkflowsSlackArchiveChannelName);

/** @internal */
export const V3WorkflowsSlackArchiveChannelName$outboundSchema: z.ZodNativeEnum<
  typeof V3WorkflowsSlackArchiveChannelName
> = V3WorkflowsSlackArchiveChannelName$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3WorkflowsSlackArchiveChannelName$ {
  /** @deprecated use `V3WorkflowsSlackArchiveChannelName$inboundSchema` instead. */
  export const inboundSchema = V3WorkflowsSlackArchiveChannelName$inboundSchema;
  /** @deprecated use `V3WorkflowsSlackArchiveChannelName$outboundSchema` instead. */
  export const outboundSchema =
    V3WorkflowsSlackArchiveChannelName$outboundSchema;
}

/** @internal */
export const V3WorkflowsSlackArchiveChannel$inboundSchema: z.ZodType<
  V3WorkflowsSlackArchiveChannel,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: V3WorkflowsSlackArchiveChannelName$inboundSchema,
});

/** @internal */
export type V3WorkflowsSlackArchiveChannel$Outbound = {
  name: string;
};

/** @internal */
export const V3WorkflowsSlackArchiveChannel$outboundSchema: z.ZodType<
  V3WorkflowsSlackArchiveChannel$Outbound,
  z.ZodTypeDef,
  V3WorkflowsSlackArchiveChannel
> = z.object({
  name: V3WorkflowsSlackArchiveChannelName$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3WorkflowsSlackArchiveChannel$ {
  /** @deprecated use `V3WorkflowsSlackArchiveChannel$inboundSchema` instead. */
  export const inboundSchema = V3WorkflowsSlackArchiveChannel$inboundSchema;
  /** @deprecated use `V3WorkflowsSlackArchiveChannel$outboundSchema` instead. */
  export const outboundSchema = V3WorkflowsSlackArchiveChannel$outboundSchema;
  /** @deprecated use `V3WorkflowsSlackArchiveChannel$Outbound` instead. */
  export type Outbound = V3WorkflowsSlackArchiveChannel$Outbound;
}

export function v3WorkflowsSlackArchiveChannelToJSON(
  v3WorkflowsSlackArchiveChannel: V3WorkflowsSlackArchiveChannel,
): string {
  return JSON.stringify(
    V3WorkflowsSlackArchiveChannel$outboundSchema.parse(
      v3WorkflowsSlackArchiveChannel,
    ),
  );
}

export function v3WorkflowsSlackArchiveChannelFromJSON(
  jsonString: string,
): SafeParseResult<V3WorkflowsSlackArchiveChannel, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3WorkflowsSlackArchiveChannel$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3WorkflowsSlackArchiveChannel' from JSON`,
  );
}
