/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  V3WorkflowsActionResponse,
  V3WorkflowsActionResponse$inboundSchema,
  V3WorkflowsActionResponse$Outbound,
  V3WorkflowsActionResponse$outboundSchema,
} from "./v3workflowsactionresponse.js";
import {
  V3WorkflowsTag,
  V3WorkflowsTag$inboundSchema,
  V3WorkflowsTag$Outbound,
  V3WorkflowsTag$outboundSchema,
} from "./v3workflowstag.js";
import {
  V3WorkflowsWorkflowFilters,
  V3WorkflowsWorkflowFilters$inboundSchema,
  V3WorkflowsWorkflowFilters$Outbound,
  V3WorkflowsWorkflowFilters$outboundSchema,
} from "./v3workflowsworkflowfilters.js";

export type V3WorkflowsUpdateWorkflowAPIResponse = {
  id?: number | undefined;
  ownerId?: string | undefined;
  title?: string | undefined;
  description?: string | undefined;
  enabled?: boolean | undefined;
  trigger?: string | undefined;
  filters?: V3WorkflowsWorkflowFilters | undefined;
  tags?: Array<V3WorkflowsTag> | undefined;
  actions?: Array<V3WorkflowsActionResponse> | undefined;
  createdAt?: string | undefined;
  createdBy?: string | undefined;
  updatedAt?: string | undefined;
  updatedBy?: string | undefined;
};

/** @internal */
export const V3WorkflowsUpdateWorkflowAPIResponse$inboundSchema: z.ZodType<
  V3WorkflowsUpdateWorkflowAPIResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int().optional(),
  owner_id: z.string().optional(),
  title: z.string().optional(),
  description: z.string().optional(),
  enabled: z.boolean().optional(),
  trigger: z.string().optional(),
  filters: V3WorkflowsWorkflowFilters$inboundSchema.optional(),
  tags: z.array(V3WorkflowsTag$inboundSchema).optional(),
  actions: z.array(V3WorkflowsActionResponse$inboundSchema).optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "owner_id": "ownerId",
    "created_at": "createdAt",
    "created_by": "createdBy",
    "updated_at": "updatedAt",
    "updated_by": "updatedBy",
  });
});

/** @internal */
export type V3WorkflowsUpdateWorkflowAPIResponse$Outbound = {
  id?: number | undefined;
  owner_id?: string | undefined;
  title?: string | undefined;
  description?: string | undefined;
  enabled?: boolean | undefined;
  trigger?: string | undefined;
  filters?: V3WorkflowsWorkflowFilters$Outbound | undefined;
  tags?: Array<V3WorkflowsTag$Outbound> | undefined;
  actions?: Array<V3WorkflowsActionResponse$Outbound> | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

/** @internal */
export const V3WorkflowsUpdateWorkflowAPIResponse$outboundSchema: z.ZodType<
  V3WorkflowsUpdateWorkflowAPIResponse$Outbound,
  z.ZodTypeDef,
  V3WorkflowsUpdateWorkflowAPIResponse
> = z.object({
  id: z.number().int().optional(),
  ownerId: z.string().optional(),
  title: z.string().optional(),
  description: z.string().optional(),
  enabled: z.boolean().optional(),
  trigger: z.string().optional(),
  filters: V3WorkflowsWorkflowFilters$outboundSchema.optional(),
  tags: z.array(V3WorkflowsTag$outboundSchema).optional(),
  actions: z.array(V3WorkflowsActionResponse$outboundSchema).optional(),
  createdAt: z.string().optional(),
  createdBy: z.string().optional(),
  updatedAt: z.string().optional(),
  updatedBy: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    ownerId: "owner_id",
    createdAt: "created_at",
    createdBy: "created_by",
    updatedAt: "updated_at",
    updatedBy: "updated_by",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3WorkflowsUpdateWorkflowAPIResponse$ {
  /** @deprecated use `V3WorkflowsUpdateWorkflowAPIResponse$inboundSchema` instead. */
  export const inboundSchema =
    V3WorkflowsUpdateWorkflowAPIResponse$inboundSchema;
  /** @deprecated use `V3WorkflowsUpdateWorkflowAPIResponse$outboundSchema` instead. */
  export const outboundSchema =
    V3WorkflowsUpdateWorkflowAPIResponse$outboundSchema;
  /** @deprecated use `V3WorkflowsUpdateWorkflowAPIResponse$Outbound` instead. */
  export type Outbound = V3WorkflowsUpdateWorkflowAPIResponse$Outbound;
}

export function v3WorkflowsUpdateWorkflowAPIResponseToJSON(
  v3WorkflowsUpdateWorkflowAPIResponse: V3WorkflowsUpdateWorkflowAPIResponse,
): string {
  return JSON.stringify(
    V3WorkflowsUpdateWorkflowAPIResponse$outboundSchema.parse(
      v3WorkflowsUpdateWorkflowAPIResponse,
    ),
  );
}

export function v3WorkflowsUpdateWorkflowAPIResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3WorkflowsUpdateWorkflowAPIResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V3WorkflowsUpdateWorkflowAPIResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3WorkflowsUpdateWorkflowAPIResponse' from JSON`,
  );
}
