/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const V3WorkflowsUpdateIncidentPriorityUpdateName = {
  SqUpdateIncidentPriority: "sq_update_incident_priority",
} as const;
export type V3WorkflowsUpdateIncidentPriorityUpdateName = ClosedEnum<
  typeof V3WorkflowsUpdateIncidentPriorityUpdateName
>;

export const V3WorkflowsUpdateIncidentPriorityUpdatePriority = {
  P1: "P1",
  P2: "P2",
  P3: "P3",
  P4: "P4",
  P5: "P5",
  Unset: "UNSET",
} as const;
export type V3WorkflowsUpdateIncidentPriorityUpdatePriority = ClosedEnum<
  typeof V3WorkflowsUpdateIncidentPriorityUpdatePriority
>;

export type V3WorkflowsUpdateIncidentPriorityUpdateData = {
  priority?: V3WorkflowsUpdateIncidentPriorityUpdatePriority | undefined;
};

export type V3WorkflowsUpdateIncidentPriorityUpdate = {
  name: V3WorkflowsUpdateIncidentPriorityUpdateName;
  data?: V3WorkflowsUpdateIncidentPriorityUpdateData | undefined;
};

/** @internal */
export const V3WorkflowsUpdateIncidentPriorityUpdateName$inboundSchema:
  z.ZodNativeEnum<typeof V3WorkflowsUpdateIncidentPriorityUpdateName> = z
    .nativeEnum(V3WorkflowsUpdateIncidentPriorityUpdateName);

/** @internal */
export const V3WorkflowsUpdateIncidentPriorityUpdateName$outboundSchema:
  z.ZodNativeEnum<typeof V3WorkflowsUpdateIncidentPriorityUpdateName> =
    V3WorkflowsUpdateIncidentPriorityUpdateName$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3WorkflowsUpdateIncidentPriorityUpdateName$ {
  /** @deprecated use `V3WorkflowsUpdateIncidentPriorityUpdateName$inboundSchema` instead. */
  export const inboundSchema =
    V3WorkflowsUpdateIncidentPriorityUpdateName$inboundSchema;
  /** @deprecated use `V3WorkflowsUpdateIncidentPriorityUpdateName$outboundSchema` instead. */
  export const outboundSchema =
    V3WorkflowsUpdateIncidentPriorityUpdateName$outboundSchema;
}

/** @internal */
export const V3WorkflowsUpdateIncidentPriorityUpdatePriority$inboundSchema:
  z.ZodNativeEnum<typeof V3WorkflowsUpdateIncidentPriorityUpdatePriority> = z
    .nativeEnum(V3WorkflowsUpdateIncidentPriorityUpdatePriority);

/** @internal */
export const V3WorkflowsUpdateIncidentPriorityUpdatePriority$outboundSchema:
  z.ZodNativeEnum<typeof V3WorkflowsUpdateIncidentPriorityUpdatePriority> =
    V3WorkflowsUpdateIncidentPriorityUpdatePriority$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3WorkflowsUpdateIncidentPriorityUpdatePriority$ {
  /** @deprecated use `V3WorkflowsUpdateIncidentPriorityUpdatePriority$inboundSchema` instead. */
  export const inboundSchema =
    V3WorkflowsUpdateIncidentPriorityUpdatePriority$inboundSchema;
  /** @deprecated use `V3WorkflowsUpdateIncidentPriorityUpdatePriority$outboundSchema` instead. */
  export const outboundSchema =
    V3WorkflowsUpdateIncidentPriorityUpdatePriority$outboundSchema;
}

/** @internal */
export const V3WorkflowsUpdateIncidentPriorityUpdateData$inboundSchema:
  z.ZodType<
    V3WorkflowsUpdateIncidentPriorityUpdateData,
    z.ZodTypeDef,
    unknown
  > = z.object({
    priority: V3WorkflowsUpdateIncidentPriorityUpdatePriority$inboundSchema
      .optional(),
  });

/** @internal */
export type V3WorkflowsUpdateIncidentPriorityUpdateData$Outbound = {
  priority?: string | undefined;
};

/** @internal */
export const V3WorkflowsUpdateIncidentPriorityUpdateData$outboundSchema:
  z.ZodType<
    V3WorkflowsUpdateIncidentPriorityUpdateData$Outbound,
    z.ZodTypeDef,
    V3WorkflowsUpdateIncidentPriorityUpdateData
  > = z.object({
    priority: V3WorkflowsUpdateIncidentPriorityUpdatePriority$outboundSchema
      .optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3WorkflowsUpdateIncidentPriorityUpdateData$ {
  /** @deprecated use `V3WorkflowsUpdateIncidentPriorityUpdateData$inboundSchema` instead. */
  export const inboundSchema =
    V3WorkflowsUpdateIncidentPriorityUpdateData$inboundSchema;
  /** @deprecated use `V3WorkflowsUpdateIncidentPriorityUpdateData$outboundSchema` instead. */
  export const outboundSchema =
    V3WorkflowsUpdateIncidentPriorityUpdateData$outboundSchema;
  /** @deprecated use `V3WorkflowsUpdateIncidentPriorityUpdateData$Outbound` instead. */
  export type Outbound = V3WorkflowsUpdateIncidentPriorityUpdateData$Outbound;
}

export function v3WorkflowsUpdateIncidentPriorityUpdateDataToJSON(
  v3WorkflowsUpdateIncidentPriorityUpdateData:
    V3WorkflowsUpdateIncidentPriorityUpdateData,
): string {
  return JSON.stringify(
    V3WorkflowsUpdateIncidentPriorityUpdateData$outboundSchema.parse(
      v3WorkflowsUpdateIncidentPriorityUpdateData,
    ),
  );
}

export function v3WorkflowsUpdateIncidentPriorityUpdateDataFromJSON(
  jsonString: string,
): SafeParseResult<
  V3WorkflowsUpdateIncidentPriorityUpdateData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3WorkflowsUpdateIncidentPriorityUpdateData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V3WorkflowsUpdateIncidentPriorityUpdateData' from JSON`,
  );
}

/** @internal */
export const V3WorkflowsUpdateIncidentPriorityUpdate$inboundSchema: z.ZodType<
  V3WorkflowsUpdateIncidentPriorityUpdate,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: V3WorkflowsUpdateIncidentPriorityUpdateName$inboundSchema,
  data: z.lazy(() => V3WorkflowsUpdateIncidentPriorityUpdateData$inboundSchema)
    .optional(),
});

/** @internal */
export type V3WorkflowsUpdateIncidentPriorityUpdate$Outbound = {
  name: string;
  data?: V3WorkflowsUpdateIncidentPriorityUpdateData$Outbound | undefined;
};

/** @internal */
export const V3WorkflowsUpdateIncidentPriorityUpdate$outboundSchema: z.ZodType<
  V3WorkflowsUpdateIncidentPriorityUpdate$Outbound,
  z.ZodTypeDef,
  V3WorkflowsUpdateIncidentPriorityUpdate
> = z.object({
  name: V3WorkflowsUpdateIncidentPriorityUpdateName$outboundSchema,
  data: z.lazy(() => V3WorkflowsUpdateIncidentPriorityUpdateData$outboundSchema)
    .optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3WorkflowsUpdateIncidentPriorityUpdate$ {
  /** @deprecated use `V3WorkflowsUpdateIncidentPriorityUpdate$inboundSchema` instead. */
  export const inboundSchema =
    V3WorkflowsUpdateIncidentPriorityUpdate$inboundSchema;
  /** @deprecated use `V3WorkflowsUpdateIncidentPriorityUpdate$outboundSchema` instead. */
  export const outboundSchema =
    V3WorkflowsUpdateIncidentPriorityUpdate$outboundSchema;
  /** @deprecated use `V3WorkflowsUpdateIncidentPriorityUpdate$Outbound` instead. */
  export type Outbound = V3WorkflowsUpdateIncidentPriorityUpdate$Outbound;
}

export function v3WorkflowsUpdateIncidentPriorityUpdateToJSON(
  v3WorkflowsUpdateIncidentPriorityUpdate:
    V3WorkflowsUpdateIncidentPriorityUpdate,
): string {
  return JSON.stringify(
    V3WorkflowsUpdateIncidentPriorityUpdate$outboundSchema.parse(
      v3WorkflowsUpdateIncidentPriorityUpdate,
    ),
  );
}

export function v3WorkflowsUpdateIncidentPriorityUpdateFromJSON(
  jsonString: string,
): SafeParseResult<
  V3WorkflowsUpdateIncidentPriorityUpdate,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3WorkflowsUpdateIncidentPriorityUpdate$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V3WorkflowsUpdateIncidentPriorityUpdate' from JSON`,
  );
}
