/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  V4SquadsSquadMember,
  V4SquadsSquadMember$inboundSchema,
  V4SquadsSquadMember$Outbound,
  V4SquadsSquadMember$outboundSchema,
} from "./v4squadssquadmember.js";

export type V4SquadsCreateSquadResponse = {
  organizationId: string;
  ownerId: string;
  id: string;
  name: string;
  slug: string;
  members: Array<V4SquadsSquadMember>;
  createdAt: string;
  createdBy: string;
};

/** @internal */
export const V4SquadsCreateSquadResponse$inboundSchema: z.ZodType<
  V4SquadsCreateSquadResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  organization_id: z.string(),
  owner_id: z.string(),
  id: z.string(),
  name: z.string(),
  slug: z.string(),
  members: z.array(V4SquadsSquadMember$inboundSchema),
  created_at: z.string(),
  created_by: z.string(),
}).transform((v) => {
  return remap$(v, {
    "organization_id": "organizationId",
    "owner_id": "ownerId",
    "created_at": "createdAt",
    "created_by": "createdBy",
  });
});

/** @internal */
export type V4SquadsCreateSquadResponse$Outbound = {
  organization_id: string;
  owner_id: string;
  id: string;
  name: string;
  slug: string;
  members: Array<V4SquadsSquadMember$Outbound>;
  created_at: string;
  created_by: string;
};

/** @internal */
export const V4SquadsCreateSquadResponse$outboundSchema: z.ZodType<
  V4SquadsCreateSquadResponse$Outbound,
  z.ZodTypeDef,
  V4SquadsCreateSquadResponse
> = z.object({
  organizationId: z.string(),
  ownerId: z.string(),
  id: z.string(),
  name: z.string(),
  slug: z.string(),
  members: z.array(V4SquadsSquadMember$outboundSchema),
  createdAt: z.string(),
  createdBy: z.string(),
}).transform((v) => {
  return remap$(v, {
    organizationId: "organization_id",
    ownerId: "owner_id",
    createdAt: "created_at",
    createdBy: "created_by",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V4SquadsCreateSquadResponse$ {
  /** @deprecated use `V4SquadsCreateSquadResponse$inboundSchema` instead. */
  export const inboundSchema = V4SquadsCreateSquadResponse$inboundSchema;
  /** @deprecated use `V4SquadsCreateSquadResponse$outboundSchema` instead. */
  export const outboundSchema = V4SquadsCreateSquadResponse$outboundSchema;
  /** @deprecated use `V4SquadsCreateSquadResponse$Outbound` instead. */
  export type Outbound = V4SquadsCreateSquadResponse$Outbound;
}

export function v4SquadsCreateSquadResponseToJSON(
  v4SquadsCreateSquadResponse: V4SquadsCreateSquadResponse,
): string {
  return JSON.stringify(
    V4SquadsCreateSquadResponse$outboundSchema.parse(
      v4SquadsCreateSquadResponse,
    ),
  );
}

export function v4SquadsCreateSquadResponseFromJSON(
  jsonString: string,
): SafeParseResult<V4SquadsCreateSquadResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V4SquadsCreateSquadResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V4SquadsCreateSquadResponse' from JSON`,
  );
}
