/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type V4StatusPagesNewStatusPageThemeColor = {
  primary?: string | undefined;
  secondary?: string | undefined;
};

/** @internal */
export const V4StatusPagesNewStatusPageThemeColor$inboundSchema: z.ZodType<
  V4StatusPagesNewStatusPageThemeColor,
  z.ZodTypeDef,
  unknown
> = z.object({
  primary: z.string().optional(),
  secondary: z.string().optional(),
});

/** @internal */
export type V4StatusPagesNewStatusPageThemeColor$Outbound = {
  primary?: string | undefined;
  secondary?: string | undefined;
};

/** @internal */
export const V4StatusPagesNewStatusPageThemeColor$outboundSchema: z.ZodType<
  V4StatusPagesNewStatusPageThemeColor$Outbound,
  z.ZodTypeDef,
  V4StatusPagesNewStatusPageThemeColor
> = z.object({
  primary: z.string().optional(),
  secondary: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V4StatusPagesNewStatusPageThemeColor$ {
  /** @deprecated use `V4StatusPagesNewStatusPageThemeColor$inboundSchema` instead. */
  export const inboundSchema =
    V4StatusPagesNewStatusPageThemeColor$inboundSchema;
  /** @deprecated use `V4StatusPagesNewStatusPageThemeColor$outboundSchema` instead. */
  export const outboundSchema =
    V4StatusPagesNewStatusPageThemeColor$outboundSchema;
  /** @deprecated use `V4StatusPagesNewStatusPageThemeColor$Outbound` instead. */
  export type Outbound = V4StatusPagesNewStatusPageThemeColor$Outbound;
}

export function v4StatusPagesNewStatusPageThemeColorToJSON(
  v4StatusPagesNewStatusPageThemeColor: V4StatusPagesNewStatusPageThemeColor,
): string {
  return JSON.stringify(
    V4StatusPagesNewStatusPageThemeColor$outboundSchema.parse(
      v4StatusPagesNewStatusPageThemeColor,
    ),
  );
}

export function v4StatusPagesNewStatusPageThemeColorFromJSON(
  jsonString: string,
): SafeParseResult<V4StatusPagesNewStatusPageThemeColor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V4StatusPagesNewStatusPageThemeColor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V4StatusPagesNewStatusPageThemeColor' from JSON`,
  );
}
