/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  V4StatusPagesComponentsComponent,
  V4StatusPagesComponentsComponent$inboundSchema,
  V4StatusPagesComponentsComponent$Outbound,
  V4StatusPagesComponentsComponent$outboundSchema,
} from "./v4statuspagescomponentscomponent.js";
import {
  V4StatusPagesComponentsComponentStatus,
  V4StatusPagesComponentsComponentStatus$inboundSchema,
  V4StatusPagesComponentsComponentStatus$Outbound,
  V4StatusPagesComponentsComponentStatus$outboundSchema,
} from "./v4statuspagescomponentscomponentstatus.js";

export type V4StatusPagesComponentsListComponentsResponse = {
  id?: number | undefined;
  type?: string | undefined;
  name?: string | undefined;
  allowSubscription?: boolean | undefined;
  description?: string | undefined;
  status?: V4StatusPagesComponentsComponentStatus | undefined;
  underMaintenance?: boolean | undefined;
  statusMaintenance?: V4StatusPagesComponentsComponentStatus | undefined;
  components?: Array<V4StatusPagesComponentsComponent> | undefined;
  isHidden?: boolean | undefined;
};

/** @internal */
export const V4StatusPagesComponentsListComponentsResponse$inboundSchema:
  z.ZodType<
    V4StatusPagesComponentsListComponentsResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    id: z.number().int().optional(),
    type: z.string().optional(),
    name: z.string().optional(),
    allowSubscription: z.boolean().optional(),
    description: z.string().optional(),
    status: V4StatusPagesComponentsComponentStatus$inboundSchema.optional(),
    underMaintenance: z.boolean().optional(),
    statusMaintenance: V4StatusPagesComponentsComponentStatus$inboundSchema
      .optional(),
    components: z.array(V4StatusPagesComponentsComponent$inboundSchema)
      .optional(),
    isHidden: z.boolean().optional(),
  });

/** @internal */
export type V4StatusPagesComponentsListComponentsResponse$Outbound = {
  id?: number | undefined;
  type?: string | undefined;
  name?: string | undefined;
  allowSubscription?: boolean | undefined;
  description?: string | undefined;
  status?: V4StatusPagesComponentsComponentStatus$Outbound | undefined;
  underMaintenance?: boolean | undefined;
  statusMaintenance?:
    | V4StatusPagesComponentsComponentStatus$Outbound
    | undefined;
  components?: Array<V4StatusPagesComponentsComponent$Outbound> | undefined;
  isHidden?: boolean | undefined;
};

/** @internal */
export const V4StatusPagesComponentsListComponentsResponse$outboundSchema:
  z.ZodType<
    V4StatusPagesComponentsListComponentsResponse$Outbound,
    z.ZodTypeDef,
    V4StatusPagesComponentsListComponentsResponse
  > = z.object({
    id: z.number().int().optional(),
    type: z.string().optional(),
    name: z.string().optional(),
    allowSubscription: z.boolean().optional(),
    description: z.string().optional(),
    status: V4StatusPagesComponentsComponentStatus$outboundSchema.optional(),
    underMaintenance: z.boolean().optional(),
    statusMaintenance: V4StatusPagesComponentsComponentStatus$outboundSchema
      .optional(),
    components: z.array(V4StatusPagesComponentsComponent$outboundSchema)
      .optional(),
    isHidden: z.boolean().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V4StatusPagesComponentsListComponentsResponse$ {
  /** @deprecated use `V4StatusPagesComponentsListComponentsResponse$inboundSchema` instead. */
  export const inboundSchema =
    V4StatusPagesComponentsListComponentsResponse$inboundSchema;
  /** @deprecated use `V4StatusPagesComponentsListComponentsResponse$outboundSchema` instead. */
  export const outboundSchema =
    V4StatusPagesComponentsListComponentsResponse$outboundSchema;
  /** @deprecated use `V4StatusPagesComponentsListComponentsResponse$Outbound` instead. */
  export type Outbound = V4StatusPagesComponentsListComponentsResponse$Outbound;
}

export function v4StatusPagesComponentsListComponentsResponseToJSON(
  v4StatusPagesComponentsListComponentsResponse:
    V4StatusPagesComponentsListComponentsResponse,
): string {
  return JSON.stringify(
    V4StatusPagesComponentsListComponentsResponse$outboundSchema.parse(
      v4StatusPagesComponentsListComponentsResponse,
    ),
  );
}

export function v4StatusPagesComponentsListComponentsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  V4StatusPagesComponentsListComponentsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V4StatusPagesComponentsListComponentsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V4StatusPagesComponentsListComponentsResponse' from JSON`,
  );
}
