/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type V4StatusPagesDeleteStatusPageByIdResponse = {
  id: number;
  name: string;
  organizationID: string;
  teamID: string;
};

/** @internal */
export const V4StatusPagesDeleteStatusPageByIdResponse$inboundSchema: z.ZodType<
  V4StatusPagesDeleteStatusPageByIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
  name: z.string(),
  organizationID: z.string(),
  teamID: z.string(),
});

/** @internal */
export type V4StatusPagesDeleteStatusPageByIdResponse$Outbound = {
  id: number;
  name: string;
  organizationID: string;
  teamID: string;
};

/** @internal */
export const V4StatusPagesDeleteStatusPageByIdResponse$outboundSchema:
  z.ZodType<
    V4StatusPagesDeleteStatusPageByIdResponse$Outbound,
    z.ZodTypeDef,
    V4StatusPagesDeleteStatusPageByIdResponse
  > = z.object({
    id: z.number().int(),
    name: z.string(),
    organizationID: z.string(),
    teamID: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V4StatusPagesDeleteStatusPageByIdResponse$ {
  /** @deprecated use `V4StatusPagesDeleteStatusPageByIdResponse$inboundSchema` instead. */
  export const inboundSchema =
    V4StatusPagesDeleteStatusPageByIdResponse$inboundSchema;
  /** @deprecated use `V4StatusPagesDeleteStatusPageByIdResponse$outboundSchema` instead. */
  export const outboundSchema =
    V4StatusPagesDeleteStatusPageByIdResponse$outboundSchema;
  /** @deprecated use `V4StatusPagesDeleteStatusPageByIdResponse$Outbound` instead. */
  export type Outbound = V4StatusPagesDeleteStatusPageByIdResponse$Outbound;
}

export function v4StatusPagesDeleteStatusPageByIdResponseToJSON(
  v4StatusPagesDeleteStatusPageByIdResponse:
    V4StatusPagesDeleteStatusPageByIdResponse,
): string {
  return JSON.stringify(
    V4StatusPagesDeleteStatusPageByIdResponse$outboundSchema.parse(
      v4StatusPagesDeleteStatusPageByIdResponse,
    ),
  );
}

export function v4StatusPagesDeleteStatusPageByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  V4StatusPagesDeleteStatusPageByIdResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V4StatusPagesDeleteStatusPageByIdResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V4StatusPagesDeleteStatusPageByIdResponse' from JSON`,
  );
}
